### ISSUE TITLE
H10: is it possible to access and set the internal memory?

### ISSUE THREAD

**Issue by lrq3000** [polarofficial/polar-ble-sdk#102]
Hello,

Thank you for providing this open SDK and extensive technical documentation!

I would like to know if it's possible to signal to H10 to access and set the internal memory with some preconfigured data types (eg, RR interval, actimetry, timestamp, ideally also ECG)? The use case would be to allow for the recording of offline sessions or to allow for the device to continue to record on the internal memory temporarily if the paired phone is unavailable and hence avoid losing data.

**Comment by JOikarinen** [comment]
@lrq3000 unfortunately at the moment it is only [HR or RR data](https://github.com/polarofficial/polar-ble-sdk/blob/9d7f21f8aa6b1967e6a3b92c9015ca8fee026578/sources/Android/android-communications/src/main/java/polar/com/sdk/api/PolarBleApi.java#L66) which can be stored to H10 internal memory.
