### ISSUE TITLE
Xcode 12.1 build issue - Module compiled with Swift 5.2 cannot be imported by the Swift 5.3 compiler

### ISSUE THREAD

**Issue by jams032** [polarofficial/polar-ble-sdk#106]
SDK is working/building successfully in xcode 11.5 but not in xcode 12.1. It shows error like : 

Module compiled with Swift 5.2 cannot be imported by the Swift 5.3 compiler: /Users/-----/polarBleSdkTestApp-ios/polar-sdk-ios/PolarBleSdk.framework/Modules/PolarBleSdk.swiftmodule/arm64-apple-ios.swiftmodule

Hope the attachemnt help you to fix.

Thanks in advance. 

![Screenshot 2020-10-25 at 12 07 26 PM](https://user-images.githubusercontent.com/13532330/97100156-a7cead00-16ba-11eb-9d4e-412d5b1e5e57.png)

![Screenshot 2020-10-25 at 12 06 48 PM](https://user-images.githubusercontent.com/13532330/97100144-91285600-16ba-11eb-9ec2-9a0c26c315cc.png)

**Comment by erkki-silvola** [comment]
Hi, sdk will be updated later, meanwhile compile from sources

**Comment by jet-lee-m** [comment]
Hi, I tried to compile from sources, but it is not possible. I used the build script from the repository (/sources/iOS/ios-communications)

I get the following error:

```
error: failed to build module 'RxSwift' from its module interface; the compiler that produced it, 'Apple Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)'
import RxSwif
```

**Comment by josephlarralde** [comment]
Please see #97 for a workaround (I had the same exact errors and now everything builds fine)
