### ISSUE TITLE
Accelerator stream mixed with ECG stream

### ISSUE THREAD

**Issue by pareeknikhil** [polarofficial/polar-ble-sdk#109]
I am trying to start the data stream from the Accelerometer sensor and also stream ECG data simultaneously using two different threads in Python using Bleak BLE library to connect with the Polar H10 device. I am using the standard PMD Data control points and starting the stream bypassing the ACC and ECG Write bits which are indicated in the official doc of the device in two separate threads. But the data is getting mixed and also, sometimes giving values way off the charts when both the streams are on, as opposed to when the device is working well when individual streams are turned on. I am just wondering is it a limitation of PolarH10 to not able to stream ACC and ECG data simultaneously? Any insight is much appreciated

**Comment by msippo** [comment]
They work simultaneously. Try this Android app https://play.google.com/store/apps/details?id=com.j_ware.polarsensorlogger
