### ISSUE TITLE
SDK bindings for .NET

### ISSUE THREAD

**Issue by vinicius-zhu** [polarofficial/polar-ble-sdk#111]
There are only libraries available for mobile devices. Would it be possible to compile the libraries to be compatible with .NET Framework so desktop applications could be developed as well?

**Comment by JOikarinen** [comment]
Unfortunately, we are only able to support Android and iOS. The SKD includes source code and you can feel free to utilize / port the code in other platforms too but that is something we are not able to provide support for.
