### ISSUE TITLE
What is the sampling frequency of Polar OH1?

### ISSUE THREAD

**Issue by neha009** [polarofficial/polar-ble-sdk#116]
What is the sampling frequency of Polar OH1?

**Comment by neha009** [comment]
while connecting to the Polar OH1 sensor using the SCAN option, I am able to show available polar devices, however, I am unable to select the device. Please suggest a solution to the same.

**Comment by JOikarinen** [comment]
@neha009 is there particular data type which frequency you are interested? You may read settings of the data type by `PolarBleApi`. For example you may read accelerometer settings by `requestAccSettings()`
