### ISSUE TITLE
Framework compatibility with Xcode 12.3

### ISSUE THREAD

**Issue by johndefalco** [polarofficial/polar-ble-sdk#117]
I've been having trouble compiling the PolarBleSdk and RxSwift frameworks with Xcode 12.3 and Swift 5.3.  I've removed the x86_64 and i386 architectures using lipo from both frameworks to get the sample app to compile, but this breaks preview. 

What's the best practice for importing the frameworks?

Thanks

John

**Comment by JOikarinen** [comment]
@johndefalco could you try option Target -> PolarBleSDKTestApp -> Build Settings -> Validate Workspace: Yes

https://stackoverflow.com/questions/63267897/building-for-ios-simulator-but-the-linked-framework-framework-was-built

**Comment by johndefalco** [comment]
Thank you, that worked!
