### ISSUE TITLE
Not able to connect Polar OH1 device using scan button

### ISSUE THREAD

**Issue by neha009** [polarofficial/polar-ble-sdk#118]
while connecting to the Polar OH1 sensor using the SCAN option, I am able to show available polar devices, however, I am unable to select the device. Please suggest a solution to the same.

**Comment by JOikarinen** [comment]
@neha009 I assume you did device scan with PolarBleApi `searchForDevice()` function?  `searchForDevice()` returns `PolarDeviceInfo` which provides MAC address (i.e. UUID on iOS side) and Polar DeviceID. You may use either  MAC address or Polar DeviceID to create connection to device with `connectToDevice()` found from PolarBleApi. 
@neha009 did I managed to answer your question?
