### ISSUE TITLE
When will new firmware of H10 supporting ECG be ready to be updated?

### ISSUE THREAD

**Issue by erikguo** [polarofficial/polar-ble-sdk#12]
We are testing the ECG feature of H10.  Then we found we should wait for the new firmware. So , when will the new one be ready?

And we find the version of firmware H10 is v1.1.8 now. When we open the Polar Beat, we didn't get the update information. So we cannot update to the latest version v2.1.9.  Could recommend some solution for us?

We are in China. 
Polar Beat v3.2.0 is downloaded from Apple App Store (China Area).  
iOS is 12.2.   iPhone 6

Thank you very much

**Comment by erkki-silvola** [comment]
Update will be available soon.

**Comment by erikguo** [comment]
Thank you for your quick reply.

How about the following problem?

And we find the version of firmware H10 is v1.1.8 now. When we open the Polar Beat, we didn't get the update information. So we cannot update to the latest version v2.1.9. Could recommend some solution for us?

We are in China.
Polar Beat v3.2.0 is downloaded from Apple App Store (China Area).
iOS is 12.2. iPhone 6

**Comment by erkki-silvola** [comment]
Currently H10 update is "blocked". It will be enabled soon and you are able to update to 3.x version.
