### ISSUE TITLE
Can i get the list of activities like we get in polar beat app in my own application by using polar-sdk for android

### ISSUE THREAD

**Issue by NehaSalve1393** [polarofficial/polar-ble-sdk#121]

**Comment by JOikarinen** [comment]
@NehaSalve1393 I assume by "activity" you mean "exercise" or "training session".  Short answer is no, but let me try to explain. 

What you can do with Polar SDK:
- with Polar SDK you can read recorded exercise from Polar H10 or Polar OH1 memory using Polar SDK file operations: [listExercises](https://github.com/polarofficial/polar-ble-sdk/blob/ed4aab70603409e7694ce9d52e1d9dfb755626a2/sources/Android/android-communications/src/main/java/polar/com/sdk/api/PolarBleApi.java#L255),  fetchExercise etc. 
- Polar H10 recording can be controlled by Polar SDK API [StartRecording](https://github.com/polarofficial/polar-ble-sdk/blob/ed4aab70603409e7694ce9d52e1d9dfb755626a2/sources/Android/android-communications/src/main/java/polar/com/sdk/api/PolarBleApi.java#L231) and StopRecording
- Polar OH1 recording cannot be controlled by Polar SDK, you shall use the physical button in Polar OH1 to start and stop exercise

What you can't do with Polar SDK:
- you cannot access exercises which are not existing in Polar H10 or Polar OH1 memory. That is generally the case if you have recorded the exercise with Polar Beat application, as Polar Beat application saves the training session data locally in phone memory. 
- If user is signed in to Polar Beat application then Polar Beat syncs the user exercises to Polar cloud. Polar cloud cannot be accessed by Polar SDK. However there is another option available if you want to get access user data in Polar cloud. Please read more in https://www.polar.com/accesslink-api/#polar-accesslink-api
