### ISSUE TITLE
Question on updating firmware of H10

### ISSUE THREAD

**Issue by poml88** [polarofficial/polar-ble-sdk#122]
Apparantly there is a new firmware 3.1.1 for the H10.

1) Any changes for the SDK? Especially the ECG part?
2) It is not shown to me in the Polar Beat App. Even though I am logged in as a use. What am I doing wrong?

**Comment by JOikarinen** [comment]
> 1. Any changes for the SDK? Especially the ECG part?
- in [3.1.1](https://support.polar.com/en/updates/polar-h10-firmware-update-311) there is enhancements how H10 handles training recording. No changes related to ECG. 

> 2. It is not shown to me in the Polar Beat App. Even though I am logged in as a use. What am I doing wrong?
- could you double check you followed these instructions: https://support.polar.com/en/support/how_can_i_update_polar_h10

**Comment by poml88** [comment]
Hi, yes, I followed those steps, still there is no update offerend fpr my H10. No idea why. Maybe I have to ask Polar Support.

**Comment by JOikarinen** [comment]
@poml88 did you try with Polar Beat or with Polar Flow app?

**Comment by poml88** [comment]
@JOikarinen I did try the Polar Beat App. I can try with the Polar Flow App as well.

**Comment by JOikarinen** [comment]
@poml88 to get the firmware update notification you shall log in as registered user in Beat app. I am not sure is that clearly mentioned in the instructions here: https://support.polar.com/en/support/how_can_i_update_polar_h10

**Comment by poml88** [comment]
@JOikarinen Yes, I am logged in as a user. Still, it does not offer me a firmware update. I can try with Polar Flow.

**Comment by poml88** [comment]
@JOikarinen I tried and the Polar Flow app is offering the update. I did not install it yet, but it seems to work with Polar Flow.
