### ISSUE TITLE
Will the iOS polar-ble-sdk work with other manufacturer's devices?  Or only Polar?

### ISSUE THREAD

**Issue by BBTMathison** [polarofficial/polar-ble-sdk#126]

**Comment by JOikarinen** [comment]
Polar BLE SDK works with other manufacturers too. However, other manufactures are not officially supported, actively developed nor tested. 

For example, If the other manufacturer BLE sensor implements Heart Service then Polar SDK may be used to listen the heart rate data. 

If you want to experiment with [example](https://github.com/polarofficial/polar-ble-sdk/tree/master/examples/example-ios) you may do something like this:

1. Set Polar filter to false
```
api.polarFilter(false)
```
2. Search will now return all available BLE devices
```
api.searchForDevice()
```
3. Use the UUID of your interest, returned by the search, to connect the BLE device
```
api.connectToDevice(<UUID>)
```
4. If the connected device supports Heart Rate Service conformed call back is called 
```
hrFeatureReady
```
