### ISSUE TITLE
Incorrect intervals stored in Google Fit

### ISSUE THREAD

**Issue by kuprel** [polarofficial/polar-ble-sdk#13]
I pulled data that was synced to Google Fit from a polar H10.  A heart rate measurement in beats per minute is stored once every second.  This is suboptimal because the H10 is actually more precise and measures RR intervals.  This information is lost when storing bpm exactly 1 second apart.  Can I suggest that the heart rate be stored at the intervals corresponding to the RR interval instead of the arbitrary 1 second interval?

Here is an example of how the heart rate is currently stored for 2 consecutive measurements exactly 1 second apart.  My suggestion is to change "startTimeNanos" and "endTimeNanos" to be the R-R interval instead of exactly 1 second.

  ```
{
   "startTimeNanos": "1555034278000000000",
   "endTimeNanos": "1555034278000000000",
   "dataTypeName": "com.google.heart_rate.bpm",
   "value": [
    {
     "fpVal": 85.0,
     "mapVal": []
    }
   ],
   "modifiedTimeMillis": "1555041337275"
  },
```
  ```
  {
   "startTimeNanos": "1555034279000000000",
   "endTimeNanos": "1555034279000000000",
   "dataTypeName": "com.google.heart_rate.bpm",
   "value": [
    {
     "fpVal": 84.0,
     "mapVal": []
    }
   ],
   "modifiedTimeMillis": "1555041337275"
  },
```

**Comment by jimmyzumthurm** [comment]
Hi @kuprel , thank you for the suggestion.
There is no plan to change how HR data is stored unfortunately. BLE Heart Rate service specification says that notifications should be send at a 1 second interval and H10 follow that logic for either sending data over BLE or storing into its internal memory.
