### ISSUE TITLE
iOS SDK release 3.0.2 is compiled without bitcode

### ISSUE THREAD

**Issue by marmarelis** [polarofficial/polar-ble-sdk#134]
After pulling the latest updates, I am confronted with the following error message from the linker:
`[...]PolarBleSdk.framework/PolarBleSdk' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. [...]`

Do you know how to fix that?
Thanks.

**Comment by JOikarinen** [comment]
The Bitcode enabled flag was accidentally changed from "default" (default is enabled) to "No" in commit 37e5f47. Fixed in 
773f229 by explicitly enabling the bitcode for PolarBleSDK target.

**Comment by marmarelis** [comment]
Thank you!

**Comment by JOikarinen** [comment]
Released the version [3.0.3](https://github.com/polarofficial/polar-ble-sdk/releases/tag/3.0.3) including the fix.
