### ISSUE TITLE
V800 Polar watch syncing problem

### ISSUE THREAD

**Issue by ankitkumarg1** [polarofficial/polar-ble-sdk#138]
V800 Polar watch not able to sync data to polarflow app , and polar sdk ios app not able to connect v800 polar watch device. Please give me solution its urgent.

**Comment by JOikarinen** [comment]
@ankitkumarg1 Please, contact customercare@polar.com about the V800 / Polar Flow app issue. You can also submit a support request at https://support.polar.com/en/support/contact_us/email_polar .
