### ISSUE TITLE
What data does the Polar iOS SDK collect?

### ISSUE THREAD

**Issue by edorphy** [polarofficial/polar-ble-sdk#147]
Privacy on the iOS platform is evolving. Developers are now required to disclose to users what information their applications collect.

What categories of data does the Polar SDK collect and what third parties, if any, is that data sent to?

For more information about this request, please see the following link: [App Privacy Details](https://developer.apple.com/app-store/app-privacy-details/)

**Comment by JOikarinen** [comment]
@edorphy thank you for your important question.

Polar SDK is not collecting any data nor sending the data to any third-party partners. It is library integrated to your app to give your application connection to the Polar sensors and access to data the Polar sensors provide. Future more the Polar SDK is not using any 3rd party libraries which would collect user sensitive data. 

It is important to mention, that Polar SDK gives your application access to types of data which may be considered as private data such as heart rate, device id etc.  If your application is collecting or sending them to 3rd parties, then it is your responsibility to correctly add privacy details for your application in App Store.
