### ISSUE TITLE
Is there an updated version of the Polar Measurement Data service? Contents are out of date

### ISSUE THREAD

**Issue by edorphy** [polarofficial/polar-ble-sdk#150]
Contents are out of date in the technical documentation of the PMD Service.

Example:
- [ ]  ECG Frame index 1 and 2 (revealed from code)
- [ ] Control Point values are not documented

**Comment by JOikarinen** [comment]
About the ECG Frame. If the type is 0 (that's the only type possible as rest of the types are reserved for future use), then the received data package contains 3 bytes of data. 3 bytes of data represents the ECG in microvolts. 
![Screenshot 2021-04-20 at 7 46 05](https://user-images.githubusercontent.com/12439855/115338942-84d60f00-a1ac-11eb-8680-740be06f4371.png)
