### ISSUE TITLE
Is there documentation on the Polar Features Configuration Service?

### ISSUE THREAD

**Issue by edorphy** [polarofficial/polar-ble-sdk#151]
Is there documentation similar to the PMD Service describing the capabilities of the PFC Service?

Looking for details / info on:
- [ ] What devices support what features
- [ ] What are the possible parameter values for the features

**Comment by JOikarinen** [comment]
@edorphy at the moment Polar Measurement Data service is the only documented and supported Polar proprietary BLE service at the moment.
