### ISSUE TITLE
Can I help in making a pure kotlin sdk?

### ISSUE THREAD

**Issue by Clement-Jean** [polarofficial/polar-ble-sdk#153]
I want to be able to use this with kotlin coroutines and flows instead of RxJava, is there any plan to do this ? if yes could I work on it ?

**Comment by JOikarinen** [comment]
@Clement-Jean it's on the road map, but not scheduled for near future. If you have interest and time on that kind of project it would be highly appreciated. 👍

**Comment by Clement-Jean** [comment]
please send me an email (on my profile) and we can discuss about it
