### ISSUE TITLE
Polar H10 -> LSL

### ISSUE THREAD

**Issue by sunshineinsandiego** [polarofficial/polar-ble-sdk#157]
**Question concerns:**
Polar device

**Description:**
Hi - I am wondering if you have any advice for streaming data from a Polar H10 monitor to LSL . I'm attempting to monitor a number of different simultaneous biosignals (including those from the H10), and the LSL protocol seems like the best bet for integration. Is this possible using a raw data stream from the H10?  Thanks!

**Comment by JOikarinen** [comment]
@sunshineinsandiego interesting question. I must confess this was first time I heart about [LSL](https://labstreaminglayer.readthedocs.io/info/intro.html)😊  With quick chat with my colleagues it appeared that there is no known projects where Polar H10 data is streamed to LSL. But I don't see any obstacles why the Polar H10 data cannot be streamed to LSL. Polar H10 provides for example heart rate, ECG and acceleration data, which I assume may be the data types supported by LSL?

**Comment by sunshineinsandiego** [comment]
Thanks JO. I ended up finding this repo: https://github.com/markspan/PolarBand2lsl which seems like you can indeed rip data from an H10 to LSL. Helpful! Thanks again.

**Comment by JOikarinen** [comment]
@sunshineinsandiego very interesting. Thank you for sharing.
