### ISSUE TITLE
Polar H10 support simultaneous connections to two different processes?

### ISSUE THREAD

**Issue by sunshineinsandiego** [polarofficial/polar-ble-sdk#164]
***Platform your question concerns:*** 
Mac OSX

***Device:***
Polar H10

**Description:**
Hi - I am developing with the Polar H10 using the BLEAK package for connections, and I'm wondering if the Polar H10 supports connections to two different processes at the same time? I'd like to record my polar data stream in one process and simultaneously visualize it. Thanks!

**Comment by JOikarinen** [comment]
Hi @sunshineinsandiego,

it is possible to create two separate BLE connections with Polar H10. So if not mistaken, you shall be able to implement the scenario you explained. 

However, you need to enable 2 BLE connections option from Polar H10 using Polar Flow application.  Here are the quick steps how to:

**Step 1:** Install Polar Flow app on your mobile and register as a user.  Within the app navigate to Training -> Start tab and choose settings icon
<img src="https://user-images.githubusercontent.com/12439855/120961656-e3f4e080-c766-11eb-94cd-f50130aa0d8f.png" width="50%" height="50%">

**Step 2:** Pair with the H10
<img src="https://user-images.githubusercontent.com/12439855/120961683-f4a55680-c766-11eb-9ed9-ae593c67bbe3.png" width="50%" height="50%">

**Step 3:** Choose settings 
<img src="https://user-images.githubusercontent.com/12439855/120961771-18689c80-c767-11eb-8d04-51af2cd148e2.png" width="50%" height="50%">

**Step 4:** Enable option "2 Bluetooth devices"
<img src="https://user-images.githubusercontent.com/12439855/120961828-3b934c00-c767-11eb-81ef-6e3217064042.png" width="50%" height="50%">

**Comment by sunshineinsandiego** [comment]
Perfect, thank you! Appreciate the help.
