### ISSUE TITLE
Acceleration data with gravity eliminated? 

### ISSUE THREAD

**Issue by ma-c-bug-pro** [polarofficial/polar-ble-sdk#167]
***Platform your question concerns:*** 
- [ ] Android 

***Device:***
- [ ] Polar Verity Sense
- [ ] Polar H10

**Description:**
Is there a way to extract clean Acceleration data from these two straps, where gravity is eliminated from data? 
If not possible for H10, is it possible for Verity Sense atleast?

**Comment by sach16795** [comment]
Hello, I want to achieve the same result. Need acceleration data with gravity eliminated. Are there any updates on this? Thanks in advance.

**Comment by jimmyzumthurm** [comment]
Hi, we currently do not provide a way of removing gravitational DC component from the accelerometer raw signal. Intention of the accelerometer raw data streaming is to provide reliable non-computed data read from our accelerometer and let the Polar SDK user interpret the data. 

For the reference, here is how the axis are defined for Verity Sense :  
![Wolfi_acc_gyro_axles_new](https://github.com/polarofficial/polar-ble-sdk/assets/62651430/d765058b-7e77-4fd3-86a0-b353a65692c2)
And H10: 
![149276237-13617f1d-34b1-4757-86e1-8bca0e064953](https://github.com/polarofficial/polar-ble-sdk/assets/62651430/2d15856d-de39-4796-a3e2-dc4208cca6eb)
