### ISSUE TITLE
Android Demo PPG Samples Incorrect

### ISSUE THREAD

**Issue by aaronhuisinga** [polarofficial/polar-ble-sdk#171]
https://github.com/polarofficial/polar-ble-sdk/blob/3197f3fa20ac1e2d38fded1b88e826f424a8a8ef/examples/example-android/androidBleSdkTestApp/app/src/main/java/polar/com/androidblesdk/MainActivity.kt#L377

It appears that the current Android example references the same offset for each of the PPG channel samples. Since this reads the same value for each PPG0/PPG1/PPG2/Ambient, my guess is this is incorrect.

**Comment by JOikarinen** [comment]
@aaronhuisinga thanks for pointing out, fixed.
