### ISSUE TITLE
PolarErrors not found

### ISSUE THREAD

**Issue by avik-efcom** [polarofficial/polar-ble-sdk#185]
***Platform your question concerns:*** 
- [ ] Android 
- [X] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [ ] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [X] Device is not relevant for this question

**Description:**
Hi there,
I try to get some information about PolarErrors but it seems there is no link on documentation for this.
Can you fix it? or send me the PolarErrors list on IOS?
![image](https://user-images.githubusercontent.com/72505851/132184519-ee257d72-cc14-416a-92af-7cd6272939bf.png)

**Comment by JOikarinen** [comment]
Hi @avik-efcom, good point.

Fixed the documentation problem in 62c8af2 and 1585e1de6572d59fe6378830b0764375c912b676.

Are you facing some particular error which you like to get more information?

**Comment by avik-efcom** [comment]
I try to understand the error "ServiceNotFound" when I ask from the exercise list, but I find it my problem cause I not ask for all SDK device permission at the start

[https://github.com/polarofficial/polar-ble-sdk/blob/1585e1de6572d59fe6378830b0764375c912b676/examples/example-ios/iosBleSdkTestApp/iosBleSdkTestApp/PolarBleSdkManager.swift#L12](url)

Thanks
