### ISSUE TITLE
buffer raw data in internal memory

### ISSUE THREAD

**Issue by merschel** [polarofficial/polar-ble-sdk#195]
***Platform your question concerns:*** 
- [ ] Android 
- [ ] iOS
- [ ] Other
- [X] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [X] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**

Hi,

is it possible to buffer raw ppg and acc data in the internal memory? If no, are there plans to do this in future versions?

**Comment by JOikarinen** [comment]
Hi @merschel,

at the moment it is not possible. I understand it would be nice feature for certain use cases, however for now there is no implementation plans.
