### ISSUE TITLE
Is it possible to stop HR calculation on the device to save battery

### ISSUE THREAD

**Issue by merschel** [polarofficial/polar-ble-sdk#196]
***Platform your question concerns:*** 
- [ ] Android 
- [ ] iOS
- [ ] Other
- [X] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [X] Polar Verity Sense
- [X] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**

Hi,

it seems that the devices calculate and send the HR data. In case the HR data is not needed, but only the raw ppg data, would it be possible to stop calculating the HR data on the devices? This could save some power.

**Comment by JOikarinen** [comment]
Hi @merschel,

it is not possible to control whether HR data is calculated or not. However, here is some thoughts about your question. If you request the stream of PPG data from Polar Verity Sense, the optical heart rate leds are on  to be able to sensor the PPG data. The consequence is that the calculation of heart rate from the PPG data is not playing a big role what comes to battery consumption neither does sending the heart rate data over BLE.

Related on your question, if you need other data types, but not PPG, PPI or HR. Then it is possible to save battery by using [SDK mode](https://github.com/polarofficial/polar-ble-sdk/blob/master/technical_documentation/SdkModeExplained.md). In SDK mode the leds are switched off.
