### ISSUE TITLE
Typo in the API documentation

### ISSUE THREAD

**Issue by seriousManual** [polarofficial/polar-ble-sdk#2]
Since I did not find another way to contact somebody responsible for the API documentation, I'm posting this here:

The (otherwise great) API documentation says that the list of daily activities can be retrieved by the URL `GET /v3/users/{user-id}/activity-transactions/{transaction-id}` yielding a response in the form:
````
{
  "activity-logs": [
    "https://www.polaraccesslink.com/v3/users/12/activity-transactions/34/activities/56",
    "https://www.polaraccesslink.com/v3/users/12/activity-transactions/34/activities/120"
  ]
}
````
Other than stated in the documentation the key for the activities URLs is not `activity-logs` but `activity-log`:

![image](https://user-images.githubusercontent.com/1330022/54823049-e44c5280-4ca6-11e9-9c08-f6ef3c90bd07.png)

**Comment by erkki-silvola** [comment]
I will forward this issue onwards.

**Comment by seriousManual** [comment]
Can you tell me how the developer support for API integrations can be reached?

**Comment by vmhirvinen** [comment]
Good catch! API Documentation should now reflect reality better for daily activities.

There is support email in top of API documentation.
