### ISSUE TITLE
Has the ecg firmwire of H10 been released?

### ISSUE THREAD

**Issue by erikguo** [polarofficial/polar-ble-sdk#20]
Hi,

Has the ecg firmwire of H10 been released? 

I didn't receive any update notification. Could you help me please？

Thank you very much

**Comment by erkki-silvola** [comment]
Yes it has been released some while ago. What is the current version in your device?

**Comment by erikguo** [comment]
My firmware is still version 1.1.8

I didn't receive update information in App Polar Beat in iPhone

What can I do?

**Comment by pablobablo** [comment]
> My firmware is still version 1.1.8
> 
> I didn't receive update information in App Polar Beat in iPhone
> 
> What can I do?

You can buy a device from another company. I already started to think about it.
