### ISSUE TITLE
What do the PPG channels represent. 

### ISSUE THREAD

**Issue by KennethEvans** [polarofficial/polar-ble-sdk#202]
***Platform your question concerns:*** 
- [x] Android 
- [ ] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [x] Polar OH1
- [x] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**
I know that the PPG data consist of 4 channels, one of which is ambient. However I do not know what the numbers represent. I wrote an app to display the four values. I was surprised to find they are all roughly constant. 

I was expecting (and want) something like the plot on my pulse oximeter or on plots I see on sites, such as Wikipedia, that discuss PPG. 

![300px-PVC_detectionUsing_PGG](https://user-images.githubusercontent.com/19721186/136678819-356c8806-493c-4b9a-be17-db6e57be7463.png)

How do I convert these signals into something that looks like top graph on that image. I would like something comparable to the ECG output from the SDK for the H10 or the third graph in the image; that is, a replacement for the ECG waveform as expected from a PPG device like the OH1 or Verity Sense.

It has been stated elsewhere that the ambient channel should be subtracted from each of the other channels,  and that they are in raw units,  not anything physical. Is there some significance to the other 3 individual channels, or can they be summed or averaged?

I am not an expert on signal processing. 

Thanks.

**Comment by JOikarinen** [comment]
Hi @KennethEvans,


>  However I do not know what the numbers represent.
- PPG signal doesn't have agreed unit. It is raw value, each manufacturer having the own scale for the value. Because of autogain feature in PolarOH1 and Polar Verity Sense there can be jumps in PPG signal during measurements. That is discussed in previous issue, see the Spikes in Polar PPG Sensor values #152 (comment)

> I wrote an app to display the four values. I was surprised to find they are all roughly constant.
- here is short section of PPG0 signal I just recorded by Polar Verity Sense:
![Polar Verity Sense channel 0](https://user-images.githubusercontent.com/12439855/136776878-fd66bf01-ad6f-4463-8bae-95a8c8befc39.png)
- from that data the peak to peak time is roughly 1333ms = 45bpm
- you shall see something like that received from PPG0, PPG1 and PPG2 channels

> It has been stated elsewhere that the ambient channel should be subtracted from each of the other channels, and that they are in raw units, not anything physical.
- That's my current understanding. I will double check this from PPG data experts.

**Comment by JOikarinen** [comment]
> * That's my current understanding. I will double check this from PPG data experts.
-  ambient channel represents the background noise caused by other light sources, so it can be used to remove the background noise from ppg channels

**Comment by JOikarinen** [comment]
one note:
- there is [known issue](https://github.com/polarofficial/polar-ble-sdk/blob/master/technical_documentation/KnownIssues.md#:~:text=PPG%20stream%20settings%20returns%20incorrect%20sampling%20rate%20when%20read%20with%20requestStreamSettings()%20function%20in%20normal%20operation%20mode.%20The%20returned%20value%20for%20sampling%20rate%20is%20135Hz%2C%20the%20returned%20sampling%20rate%20should%20be%2055Hz.%20The%20problem%20is%20only%20in%20Polar%20Verity%20Sense%20firmware%20v.1.1.5) with Polar Verity Sense, PPG data is actually sampled with sampling rate of 55Hz.

**Comment by KennethEvans** [comment]
> one note:
> 
> * there is [known issue](https://github.com/polarofficial/polar-ble-sdk/blob/master/technical_documentation/KnownIssues.md#:~:text=PPG%20stream%20settings%20returns%20incorrect%20sampling%20rate%20when%20read%20with%20requestStreamSettings()%20function%20in%20normal%20operation%20mode.%20The%20returned%20value%20for%20sampling%20rate%20is%20135Hz%2C%20the%20returned%20sampling%20rate%20should%20be%2055Hz.%20The%20problem%20is%20only%20in%20Polar%20Verity%20Sense%20firmware%20v.1.1.5) with Polar Verity Sense, PPG data is actually sampled with sampling rate of 55Hz.

That's unfortunate. Coding with branches to handle specific devices and firmwares is hard to maintain and easily broken.

Is there a way to know what sampling rate you're **actually getting** without doing something like counting how many samples you get in some time period. Obviously the plotting is going to be wrong if you get something that wasn't requested or expected.

**Comment by JOikarinen** [comment]
> So I guess the answer to my question is there is no way to tell what sampling rate you will actually get (for PPG).
- unfortunately because the known issues on OH1 and Polar Verity Sense you cannot trust on the frequency you request the PPG streams
- so I see only two options: either you calculate the frequency from received PPG timestamps, was that something which is not suitable in your application? Or the dummy approach, using the known frequencies, which are 130Hz for OH1 and 55Hz for Polar Verity Sense. 

> However the real problem is that the data are very susceptible to motion (on top of the fact there is a large DC component). I don't find the results useful for an app that does the PPG equivalent of an ECG, what I want.
- the motion is the core problem with the optical heart rate measurement. There is no other help provided by SDK than the PPI, which is not exactly what you want, right? Of course the PPI is also sensitive for the motion, so the motion problem is still existing in PPI stream.

**Comment by arezomar** [comment]
Hi there,
I am writing my final university year dissertation on validity of Polar H10 and Verity. I had the same intial question as kenneth, although I am struggling to find an answer. why do we get 3 different channels(PPG0, PPG1, PPG2) and what does each channel mean? what do they represent?
Thanks

**Comment by PChiericoUPV** [comment]
Hello
I would like to understand if the PPG signal is inverted, as the systolic phase seems to be consistent with the literature only when I invert the signal on the Y-axis. Additionally, regarding the three PPG channels, does Ch0 represent a combination of the six measurements?

**Comment by ejpretty** [comment]
> https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7085621/
> 
> This article explains the data recovered by the ppg sensors. Each channel represents: green, red and infrared light transmitted to the skin tissue and the data is captured by its receptor.

this is not true, this paper is referring to a sensor they constructed in which they capture those three different wavelengths. 

the question of what the three non-ambient channels represent (is it different wavelengths, or something else?) has not been answered in this thread.

**Comment by beatrizbonafini** [comment]
> > https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7085621/
> > This article explains the data recovered by the ppg sensors. Each channel represents: green, red and infrared light transmitted to the skin tissue and the data is captured by its receptor.
> 
> this is not true, this paper is referring to a sensor they constructed in which they capture those three different wavelengths.
> 
> the question of what the three non-ambient channels represent (is it different wavelengths, or something else?) has not been answered in this thread.

You are correct about the literal purpose of the article; however, if you read the introduction, it mentions, "PPG uses a sensor composed of light-emitting and light-receiving elements. When light is irradiated to the body tissue by the light-emitting element, it is transmitted, reflected, and scattered by the Beer–Lambert law in the tissues, blood vessels, and blood of the body and detected by the light-receiving element [5,6]. **In general, a green, red, or infrared light-emitting diode (LED) is used as a light-emitting unit, and a photo diode (PD) is used for a light-receiving unit [7].** LEDs used for PPG measurements generally have a wavelength of 400–1000 nm." It was in this sense that I suggested reading the article and not to solve this issue literally. It was a kind way to help those who are experiencing difficulties. I hope you can solve your problem.
