### ISSUE TITLE
Polar H10 Accelerometer is actually a Gyroscope?

### ISSUE THREAD

**Issue by larskrakhecke** [polarofficial/polar-ble-sdk#204]
***Platform your question concerns:*** 
- [ ] Android 
- [ ] iOS
- [ ] Other
- [x] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [ ] Polar Verity Sense
- [x] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**
After some trial and error I've managed to get the Polar H10 to stream Accelerometer-Data as per the Start Stream section of the PDM Specification (https://github.com/polarofficial/polar-ble-sdk/blob/master/technical_documentation/Polar_Measurement_Data_Specification.pdf)

However it appears to me that the data I receive through the stream for the X/Y/Z-Axis does not represent a change in linear acceleration but instead shows me how the Polar H10 at my chest is currently rotated? Bending forward / backward directly affects the Z-Axis value, but not like in an acceleration but in a rotation.

I verified this effect by taking a look at the graph for ACC in the Polar Sensor Logger App (https://play.google.com/store/apps/details?id=com.j_ware.polarsensorlogger&hl=de&gl=US) and there as well the Accelerometer stream shows the current rotation instead of a linear acceleration force.

What am I doing wrong here? I do expect the accelerometer to show me a linear acceleration and not a rotation state.

**Comment by JOikarinen** [comment]
No problem @larskrakhecke👍
