### ISSUE TITLE
Updated Android version-12 phone cannot connect to Polar device using the example app

### ISSUE THREAD

**Issue by khangdang4vn** [polarofficial/polar-ble-sdk#214]
***Platform your question concerns:*** 
- [x] Android 
- [ ] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [x] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**
Hello, I have been using the example app (integrated with our application) to connect with Polar Verity Sense, well tested with Android Version 11 phone (Samsung Galaxy S21).

Everything in the example app had been working well until I upgraded my phone to Version 12 last week. I upgraded the Project Structure of our application in Android Studio. At this point, the example app (with the latest sdk) could not connect to Polar device.

Full logs produced by the Polar SDK as below:

> canCallback.scannerIdleState(BDScanCallback.kt:135)
>         at com.polar.androidcommunications.enpoints.ble.bluedroid.host.BDScanCallback.commandState(BDScanCallback.kt:114)
>         at com.polar.androidcommunications.enpoints.ble.bluedroid.host.BDScanCallback.changeState(BDScanCallback.kt:128)
>         at com.polar.androidcommunications.enpoints.ble.bluedroid.host.BDScanCallback.callStartScanL(BDScanCallback.kt:301)
>         at com.polar.androidcommunications.enpoints.ble.bluedroid.host.BDScanCallback.startLScan(BDScanCallback.kt:275)
>         at com.polar.androidcommunications.enpoints.ble.bluedroid.host.BDScanCallback.startScanning(BDScanCallback.kt:256)
>         at com.polar.androidcommunications.enpoints.ble.bluedroid.host.BDScanCallback.scannerScanningState(BDScanCallback.kt:201)
>         at com.polar.androidcommunications.enpoints.ble.bluedroid.host
> ...
> ...
> ...
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
> D/AndroidRuntime: Shutting down VM
> E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: edu.ucsd.calab.extrasensory, PID: 7285
>     java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available

I guess I run into the same issue in this post https://github.com/polarofficial/polar-ble-sdk/issues/203

For my Project Structure:

> Android Gradle Plugin Version: 7.0.3
> Gradle Version: 7.3-rc-1
> compileSdkVersion: 31
> Some dependencies relating to kotlin and rxjava:
> dependencies {
>     implementation 'androidx.activity:activity-ktx:1.4.0' 
>     implementation 'androidx.fragment:fragment-ktx:1.4.0' 
>     implementation 'androidx.work:work-runtime-ktx:2.7.1'
>     implementation files('libs/polar-ble-sdk.aar')
>     implementation 'io.reactivex.rxjava3:rxjava:3.1.2'
>     implementation 'io.reactivex.rxjava3:rxandroid:3.0.0'
>     implementation 'commons-io:commons-io:20030203.000550'
>     // Only needed if FEATURE_POLAR_FILE_TRANSFER used
>     implementation 'com.google.protobuf:protobuf-javalite:3.14.0'
>     implementation "androidx.core:core-ktx:1.7.0"
>     implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.0'
>     implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.0'
>     implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0-RC'
>     implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.0-RC'

**Comment by JOikarinen** [comment]
Hi @khangdang4vn, 

the [Bluetooth permissions](https://developer.android.com/guide/topics/connectivity/bluetooth/permissions) scheme is updated on Android 12.

So if you have changed your application target to SDK 31 and then running your app on Android 12 device, you need to make some changes on permission. The [example app](https://github.com/polarofficial/polar-ble-sdk/tree/master/examples/example-android/androidBleSdkTestApp) is up to date and can be used as reference. 

Your manifest shall look something like this:
```
   <!-- Polar SDK needs Bluetooth scan permission to search for BLE devices.-->
    <uses-permission
        android:name="android.permission.BLUETOOTH_SCAN"
        android:usesPermissionFlags="neverForLocation" />

    <!-- Polar SDK needs Bluetooth connect permission to connect for found BLE devices.-->
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />

    <!-- Allows Polar SDK to connect to paired bluetooth devices. Legacy Bluetooth permission,
     which is needed on devices with API 30 (Android Q) or older. -->
    <uses-permission
        android:name="android.permission.BLUETOOTH"
        android:maxSdkVersion="30" />

    <!-- Allows Polar SDK to discover and pair bluetooth devices. Legacy Bluetooth permission,
     which is needed on devices with API 30 (Android Q) or older. -->
    <uses-permission
        android:name="android.permission.BLUETOOTH_ADMIN"
        android:maxSdkVersion="30" />

    <!-- Polar SDK needs the fine location permission to get results for Bluetooth scan. Request
    fine location permission on devices with API 30 (Android Q). -->
    <uses-permission
        android:name="android.permission.ACCESS_FINE_LOCATION"
        android:maxSdkVersion="30" />

   <!-- The coarse location permission is needed, if fine location permission is requested. Request
     coarse location permission on devices with API 30 (Android Q). -->
    <uses-permission
        android:name="android.permission.ACCESS_COARSE_LOCATION"
        android:maxSdkVersion="30" />

```

Note, that if your app needs COARSE or FINE location permissions then remove the maxSdkVersion argument. 

In addition to Manifest changes the permission query on code side may look something like this, snapshot from [example app](https://github.com/polarofficial/polar-ble-sdk/blob/4e5d091c5cbae6cbd1110b57f2dd89c98ffa6045/examples/example-android/androidBleSdkTestApp/app/src/main/java/com/polar/androidblesdk/MainActivity.kt#L546):
```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            requestPermissions(arrayOf(Manifest.permission.BLUETOOTH_SCAN, Manifest.permission.BLUETOOTH_CONNECT), PERMISSION_REQUEST_CODE)
        } else {
            requestPermissions(arrayOf(Manifest.permission.ACCESS_FINE_LOCATION), PERMISSION_REQUEST_CODE)
        }
    }
    requestPermissions(arrayOf(Manifest.permission.ACCESS_COARSE_LOCATION), PERMISSION_REQUEST_CODE)
}
 ```
 
 Please let me know if the above did not help you, lets then investigate more.
