### ISSUE TITLE
How to sync data from built-in memory of Polar Verity Sense

### ISSUE THREAD

**Issue by khangdang4vn** [polarofficial/polar-ble-sdk#217]
***Platform your question concerns:*** 
- [x] Android 
- [ ] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [x] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**
Hi @JOikarinen,

I read here [https://www.polar.com/us-en/products/accessories/polar-verity-sense?gclid=CjwKCAiAksyNBhAPEiwAlDBeLGObnF-Kb-H9J5DfpEMMBDSHncADP5xtaUpBojtamZAcsYqtCGjW_hoC9PsQAvD_BwE](url) saying that. "Polar Verity Sense has a built-in memory that can store up to 600 hours of training data."

Is there any code to get the previous data stored in the Polar device?

Thank you.

**Comment by JOikarinen** [comment]
@khangdang4vn yes, it is possible. However, there is constraints that first you need to register OH1 or Polar Verity Sense device with Polar Flow Ecosystem. Here are the steps:

1. First the [OH1](https://support.polar.com/e_manuals/OH1/Polar_OH1_user_manual_English/Content/Setting-up-your-OH1.htm) or [VeritySense](https://support.polar.com/e_manuals/verity-sense/polar-verity-sense-user-manual-english/setting-up-your-verity-sense.htm) needs to be registered to Polar Flow ecosystem.
2. Do exercise recording(s) with [OH1](https://support.polar.com/e_manuals/OH1/Polar_OH1_user_manual_English/Content/Start-a-Training-Session.htm) or [VeritySense](https://support.polar.com/e_manuals/verity-sense/polar-verity-sense-user-manual-english/training-in-recording-mode.htm).  
3. List exercises with API function [listExercises](https://github.com/polarofficial/polar-ble-sdk/blob/78609b756fe500154b8b129b16ace64bd35c33b9/sources/Android/android-communications/library/src/sdk/java/com/polar/sdk/api/PolarBleApi.java#L309)
4. Read exercise with API function [fetchExercise](https://github.com/polarofficial/polar-ble-sdk/blob/78609b756fe500154b8b129b16ace64bd35c33b9/sources/Android/android-communications/library/src/sdk/java/com/polar/sdk/api/PolarBleApi.java#L322)
