### ISSUE TITLE
How many OH1 can connect simultaneously to Android 8.0 devices?

### ISSUE THREAD

**Issue by kmatsumotoA** [polarofficial/polar-ble-sdk#22]
Hello
I am developing an application using "polar-sdk-android" now.
I have one question.
How many OH1 can connect up to Android 8.0 devices?
Now I can not test because I have only two.
I'm glad if you could tell me.
Thank you.

**Comment by erkki-silvola** [comment]
Hi,

It depends on many things how many connections are supported and actually works. But roughly it is between 5-10 connections.
