### ISSUE TITLE
Polar-BLE-SDK for MATLAB

### ISSUE THREAD

**Issue by shx2pi** [polarofficial/polar-ble-sdk#220]
***Platform your question concerns:*** 
- [ ] Android 
- [ ] iOS
- [ ] Other
- [x] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [ ] Polar Verity Sense
- [x] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**

**Comment by shx2pi** [comment]
Is there polar ble sdk for matlab?

**Comment by JOikarinen** [comment]
Unfortunately, we are only able to support Android and iOS. The SDK includes source code and you can feel free to utilize / port the code in other platforms too but that is something we are not able to provide support for.
