### ISSUE TITLE
I didn't receive update information in App Polar Beat in iPhone

### ISSUE THREAD

**Issue by erikguo** [polarofficial/polar-ble-sdk#23]
My firmware is still version 1.1.8

I didn't receive update information in App Polar Beat in iPhone

What can I do?

**Comment by erkki-silvola** [comment]
What is the beat version?

**Comment by erikguo** [comment]
The Polar Beat version is v 3.3.1

**Comment by erkki-silvola** [comment]
It should offer update, I don't know why it does not. I would suggest to contact polar support for this.
