### ISSUE TITLE
Connect to H10 and get ECG data w/o using the SDK

### ISSUE THREAD

**Issue by mjunkmyjunk** [polarofficial/polar-ble-sdk#245]
***Platform your question concerns:*** 
- [ ] Android 
- [x ] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [ ] Polar Verity Sense
- [x ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**
I'm not well versed in RxSwift and thus am wondering if it's at all possible to get the ECG data directly from the H10 w/o using the Polar SDK? eg: connecting to the PMD_MTU service and then getting "notify" of all values that comes out of the ECG?

I tried doing that, however the documentation isn't as clear (to me) on what "codes" to send to the PMD_CP to get it to start to stream.

I tried sending it 0x01 and 0x02 if I remember correctly.

Tx

**Comment by JOikarinen** [comment]
Hi @mjunkmyjunk,

yes, that is possible.  The instructions can be found in [Polar Measurement data specification](https://github.com/polarofficial/polar-ble-sdk/blob/master/technical_documentation/Polar_Measurement_Data_Specification.pdf)

You may check the Request Stream Settings and Start Stream sequence diagrams at the bottom of the document. First you could read the settings of H10 for ECG and then start the stream by using the read settings. In the document the is example how to read ACC settings and how to start ACC stream for H10. In your case the ACC is replaced by the ECG.
