### ISSUE TITLE
can't resolve symbol _$S7RxSwift28SerialDispatchQueueSchedulerCMa

### ISSUE THREAD

**Issue by wujunyang** [polarofficial/polar-ble-sdk#25]
dyld: lazy symbol binding failed: can't resolve symbol _$S7RxSwift28SerialDispatchQueueSchedulerCMa in

This error is reported by XCode 10.1 above？

**Comment by erkki-silvola** [comment]
I have not seen this my self and I am using latest Xcode currently. Do you get this when building polarBleSdkTestApp?
