### ISSUE TITLE
com.polar.sdk.api.errors.PolarDeviceDisconnected

### ISSUE THREAD

**Issue by KennethEvans** [polarofficial/polar-ble-sdk#250]
**Platform on which you observed the bug:** 
- [x] Android 
- [ ] iOS
- [ ] Other
- [ ] Platform is not relevant for this bug

**Device on which you observed the bug:**
- [ ] Polar OH1
- [ ] Polar Verity Sense
- [x] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this bug

I am getting PolarDeviceDisconnected errors in my ECG app.  This is something new. It recovers and continues getting ECG values, however.

Log attached.

[KE.Net-ECG-Exception2022-03-11.txt](https://github.com/polarofficial/polar-ble-sdk/files/8234740/KE.Net-ECG-Exception2022-03-11.txt)

**Comment by KennethEvans** [comment]
It hasn't happened again. May be a sometime thing.

**Comment by jimmyzumthurm** [comment]
Hi @KennethEvans 
Have you noticed this behavior since your original report ?

**Comment by dmoonfire** [comment]
Sadly, @KennethEvans  passed on July 30 due to heart complications. I'm monitoring his account (you can verify on his profile) if you have questions, but I'm not able to verify anything related to his Polar device so this issue is safe to close.

**Comment by jimmyzumthurm** [comment]
Hi @dmoonfire , thank you for letting us know. We're sorry to hear about Kenneth's passing. If there are any questions or concerns in the future, please feel free to contact us.
