### ISSUE TITLE
Change MTU value with Python BleakClient UUID

### ISSUE THREAD

**Issue by AlexandreDuval** [polarofficial/polar-ble-sdk#256]
***Platform your question concerns:*** 
- [ ] Android 
- [ ] iOS
- [x] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [ ] Polar Verity Sense
- [x] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**
I have seen that we can change the MTU value to a minimum to minimize the latency: 
https://github.com/polarofficial/polar-ble-sdk/blob/49f993a917aa461267c8c93d42d31d1972090b0c/sources/Android/android-communications/library/src/sdk/java/com/polar/sdk/api/PolarBleApi.java#L126

I am using Python on Ubuntu. Connecting and communicating with the device using the library BleakClient. I can read ECG value, etc.

I have tried to call the write_gatt_char() from BleackClient but the MTU characteristic cannot be written.

Can you help me with that?

Thank you

**Comment by JOikarinen** [comment]
Hi @AlexandreDuval, 

here is the traditional disclaimer I must say questions not related exactly to SDK:

unfortunately, we are only able to support Android and iOS. The SDK includes source code and you can feel free to utilize / port the code in other platforms too but that is something we are not able to provide support for.

I think, setting the MTU is based on the platform you are working, for example Android platform opens the API to the  bluetooth stack allowing the MTU negotiation. Whereas iOS platform doesn't support MTU change.
