### ISSUE TITLE
Commercial application using Verity Sense - need to purchase in bulk

### ISSUE THREAD

**Issue by johndefalco** [polarofficial/polar-ble-sdk#258]
***Platform your question concerns:*** 
- [ ] Android 
- [ ] iOS
- [ ] Other
- [X ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [X ] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

My company makes an application that uses the Verity Sense and we are doing large-scale deployments of hundreds of sensors to multiple sites.  I can't find a point of contact on the Polar website for this type of purchasing.  Can you point me in the right direction?

Thanks

John

**Comment by JOikarinen** [comment]
Hi @johndefalco, 

sorry for a delayed response. Best way to proceed is that you contact with [b2bhelpdesk@polar.com](mailto:b2bhelpdesk@polar.com). The [b2bhelpdesk@polar.com](mailto:b2bhelpdesk@polar.com) is able to give the best contact based on your location.
