### ISSUE TITLE
H10 internal RR recording - possible to get recording's start time? 

### ISSUE THREAD

**Issue by SanjeevKSharma** [polarofficial/polar-ble-sdk#269]
***Platform your question concerns:*** 
- [ x] Android 

***Device:***
- [ x] Polar H10

**Description:**
I've gotten the example app modded to get RR recordings and fetch them off the sensor.

Is it possible to get a timestamp for when the recording started?
Or maybe when the recording ended plus the total length of the recording?

**Comment by JOikarinen** [comment]
Hi @SanjeevKSharma, sorry for slow response on your question. 

SDK do not provide start time or end time of the recording. So I would recommend you timestamps the moments in your app when you [startRecording](https://github.com/polarofficial/polar-ble-sdk/blob/8f52ccf514de36cf5b5d6258b46f0a0f06754208/sources/Android/android-communications/library/src/sdk/java/com/polar/sdk/api/PolarBleApi.java#L289) and [stopRecording](https://github.com/polarofficial/polar-ble-sdk/blob/8f52ccf514de36cf5b5d6258b46f0a0f06754208/sources/Android/android-communications/library/src/sdk/java/com/polar/sdk/api/PolarBleApi.java#L302)
