### ISSUE TITLE
Support for Polar Watches

### ISSUE THREAD

**Issue by tylerbGCI** [polarofficial/polar-ble-sdk#273]
As far as i can tell, i cannot gain access to the sensors on my new Grit Pro x using this sdk. Are there plans for future support or can someone direct me to supported tools/examples? Can be for iOS/Android/Linux that would allow me to access stream sensor data and/or pull cached files from the device.

**Comment by JOikarinen** [comment]
Hi @tylerbGCI, unfortunately only the Polar sensors are supported with the SDK at the moment. The supported sensors are [H10](https://www.polar.com/en/sensors/h10-heart-rate-sensor), [H9](https://www.polar.com/en/sensors/h9-heart-rate-sensor), OH1 and [VeritySense](https://www.polar.com/en/products/accessories/polar-verity-sense/).
