### ISSUE TITLE
Streaming data with Python

### ISSUE THREAD

**Issue by Edouard99** [polarofficial/polar-ble-sdk#281]
***Platform your question concerns:*** 
- [ ] Android 
- [ ] iOS
- [x] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [ ] Polar Verity Sense
- [x] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

Hi,
I am trying to stream the data from the Polar H10 using BLE communcation. I am trying for now to reproduce the results furnished in the doc https://github.com/polarofficial/polar-ble-sdk/blob/master/technical_documentation/Polar_Measurement_Data_Specification.pdf 
I am using GATT, I am trying to read the PMD control point client characteristic conf descriptor (UUID FB005C81-02E7-F387-1CAD-8ACD2D8DF0C8). I am reading "0f05000000000000000000000000000000".
I think I should be reading "0f6E000000000000000000000000000000". I also tried to send "0102" to FB005C81-02E7-F387-1CAD-8ACD2D8DF0C8 to get the streaming setting but I am obtaining no response from the client. 
The problem may come from the "Pre Requisite" mentionned in the doc but I don't understand what I am supposed to do when they write "CCC write".

Thank you for your time

**Comment by Edouard99** [comment]
My bad I finally suceeded to activate notification and it is working properly

**Comment by JanMenssen** [comment]
Dear Edoard

I have the same problem, I want to read ECG data from the H10 using BLE using the arduinoBLE.
Reading the UID FB005C81-02E7-F387-1CAD-8ACD2D8DF0C8 results also in 0x0F 0x05 0x00

Writing to 0x01, 0x00 to the same UUID seems succesful, however no update status and reading again results in the same message and not in a control point response starting with 0xF0 0x01 0x00

So I guess, I should also activate the notification as mentioned in your post, however I do not know how to do this ?
So please, let me know how you solved it

regards - jan

**Comment by JanMenssen** [comment]
problem solved ;-)

**Comment by dara1400** [comment]
> problem solved ;-)

Hello

Could you explain how did you manage to solve the problem?

**Comment by dara1400** [comment]
> My bad I finally suceeded to activate notification and it is working properly

Nice,
Could you explain how?

**Comment by ccwang65** [comment]
I want to know if it is possible to use SDKMode to read ECG at maximum sampling rate. Appreciate if any one want to share.
