### ISSUE TITLE
best practice for pairing to multiple sensors in iOS app

### ISSUE THREAD

**Issue by johndefalco** [polarofficial/polar-ble-sdk#282]
***Platform your question concerns:*** 
- [ ] Android 
- [X ] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [X ] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

What is the best practice for connecting to multiple Verity Sense sensors in iOS?  Should I create an instance of the PolarBleSdkManager class for each sensor, or should I create one instance of PolarBleSdkManager and manage all of the sensor connections within that class instance.  I am using accelerometer and magnetometer data, so I have to pair to the sensors and cannot just rely on HR broadcast.

Thanks for your help

John

**Comment by JOikarinen** [comment]
Hi @johndefalco,

I would recommend you have one  instance of PolarBleSdkManager. Using that instance you may open multiple connections by [connectToDevice](https://github.com/polarofficial/polar-ble-sdk/blob/9923d9aec69c3d2f174cc790c44c031e31ec12e1/sources/iOS/ios-communications/Sources/PolarBleSdk/sdk/api/PolarBleApi.swift#L150) API. 

Each of the device related operation has device identifier as a parameter, to separate which device the operation is related to. The device identifier is either Polar DeviceId or the bluetooth mac address of the device. 

Typical use of SDK is that first the instance of the PolarBleSdkManager is created, probably at the app startup or only for the lifecycle of some component (e.g. view), what ever suites for you. Second the devices are search with [searchForDevice](https://github.com/polarofficial/polar-ble-sdk/blob/9923d9aec69c3d2f174cc790c44c031e31ec12e1/sources/iOS/ios-communications/Sources/PolarBleSdk/sdk/api/PolarBleApi.swift#L163) and from the searched devices you may pick the ones to connect. 


Typical
