### ISSUE TITLE
The problem of acquiring abnormal heart rate

### ISSUE THREAD

**Issue by wujunyang** [polarofficial/polar-ble-sdk#29]
{\"hr\": \"157\", \"mt\": 1557898344448}, {\"hr\": \"157\", \"mt\": 1557898345449}, {\"hr\": \"157\", \"mt\": 1557898346448}, {\"hr\": \"157\", \"mt\": 1557898347448}, {\"hr\": \"-7\", \"mt\": 1557898348448}, {\"hr\": \"-14\", \"mt\": 1557898349448}, {\"hr\": \"-21\", \"mt\": 1557898350448}, {\"hr\": \"-28\", \"mt\": 1557898351448}, {\"hr\": \"-35\", \"mt\": 1557898352448}, {\"hr\": \"-42\", \"mt\": 1557898353448}, {\"hr\": \"-49\", \"mt\": 1557898354448}, {\"hr\": \"-56\", \"mt\": 1557898355448}, {\"hr\": \"-63\", \"mt\": 1557898356448}, {\"hr\": \"-70\", \"mt\": 1557898357448}, {\"hr\": \"-77\", \"mt\": 1557898358448}, {\"hr\": \"-84\", \"mt\": 1557898359448}, {\"hr\": \"-91\", \"mt\": 1557898360448}, {\"hr\": \"-98\", \"mt\": 1557898361448}, {\"hr\": \"-105\", \"mt\": 1557898362448}, {\"hr\": \"-112\", \"mt\": 1557898363448}, {\"hr\": \"-119\", \"mt\": 1557898364448}, {\"hr\": \"-126\", \"mt\": 1557898365448}, {\"hr\": \"-133\", \"mt\": 1557898366448}, {\"hr\": \"-140\", \"mt\": 1557898367448}, {\"hr\": \"-147\", \"mt\": 1557898368448}, {\"hr\": \"1\", \"mt\": 1557898369448}, {\"hr\": \"0\", \"mt\": 1557898370448}, {\"hr\": \"1\", \"mt\": 1557898371448}, {\"hr\": \"0\", \"mt\": 1557898372448}, {\"hr\": \"0\", \"mt\": 1557898373448}, {\"hr\": \"1\", \"mt\": 1557898374448}, {\"hr\": \"0\", \"mt\": 1557898375448}, {\"hr\": \"0\", \"mt\": 1557898376448}, {\"hr\": \"0\", \"mt\": 1557898377448}, {\"hr\": \"1\", \"mt\": 1557898378448}, {\"hr\": \"1\", \"mt\": 1557898379448}, {\"hr\": \"1\", \"mt\": 1557898380448}, {\"hr\": \"1\", \"mt\": 1557898381447}, {\"hr\": \"1\", \"mt\": 1557898382448}, {\"hr\": \"0\", \"mt\": 1557898383448}, {\"hr\": \"1\", \"mt\": 1557898384448}, {\"hr\": \"253\", \"mt\": 1557898385448}, {\"hr\": \"337\", \"mt\": 1557898386448}, {\"hr\": \"169\", \"mt\": 1557898387448}, {\"hr\": \"164\", \"mt\": 1557898388448}, {\"hr\": \"164\", \"mt\": 1557898389448}, {\"hr\": \"165\", \"mt\": 1557898390448}, {\"hr\": \"165\", \"mt\": 1557898391448}, {\"hr\": \"166\", \"mt\": 1557898392448}, {\"hr\": \"167\"

{\"hr\": \"0\", \"mt\": 1561457454862}, {\"hr\": \"0\", \"mt\": 1561457455862}, {\"hr\": \"0\", \"mt\": 1561457456862}, {\"hr\": \"0\", \"mt\": 1561457457862}, {\"hr\": \"1\", \"mt\": 1561457458860}, {\"hr\": \"1\", \"mt\": 1561457459860}, {\"hr\": \"0\", \"mt\": 1561457460860}, {\"hr\": \"1\", \"mt\": 1561457461860}, {\"hr\": \"1\", \"mt\": 1561457462860}, {\"hr\": \"193\", \"mt\": 1561457463860}, {\"hr\": \"205\", \"mt\": 1561457464860}, {\"hr\": \"217\", \"mt\": 1561457465860}, {\"hr\": \"229\", \"mt\": 1561457466860}, {\"hr\": \"241\", \"mt\": 1561457467860}, {\"hr\": \"253\", \"mt\": 1561457468860}, {\"hr\": \"265\", \"mt\": 1561457469860}, {\"hr\": \"277\", \"mt\": 1561457470860}, {\"hr\": \"289\", \"mt\": 1561457471860}, {\"hr\": \"301\", \"mt\": 1561457472860}, {\"hr\": \"313\", \"mt\": 1561457473860}, {\"hr\": \"325\", \"mt\": 1561457474860}, {\"hr\": \"337\", \"mt\": 1561457475860}, {\"hr\": \"349\", \"mt\": 1561457476860}, {\"hr\": \"181\", \"mt\": 1561457477860}, {\"hr\": \"181\", \"mt\": 1561457478860}, {\"hr\": \"179\", \"mt\": 1561457479860}, {\"hr\": \"179\", \"mt\": 1561457480860}, {\"hr\": \"178\", \"mt\": 1561457481860}, {\"hr\": \"179\", \"mt\": 1561457482860}, {\"hr\": \"179\", \"mt\": 1561457483860}, {\"hr\": \"180\", \"mt\": 

Is there any abnormality in heart rate obtained by SDK? From my current data, we can see that there will be some HR over 200, and some HR values are negative. What is the general cause of this? It seems that the data will continue to be superimposed or decreases, for example, the data of the instance is 12.

**Comment by erkki-silvola** [comment]
Which platform? Have you tried any other application for reference?
