### ISSUE TITLE
Is it Possible to read the Ant+ id from the device?

### ISSUE THREAD

**Issue by HaveANiceDay33** [polarofficial/polar-ble-sdk#290]
***Platform your question concerns:*** 
- [x] Android 
- [x] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [x] Polar Verity Sense
- [x] Polar H10
- [x] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

We are working with a device that requires an Ant+ id to pair with a HRM. Is there a way to read the Ant+ id directly off of the device?

**Comment by JOikarinen** [comment]
Hi @HaveANiceDay33, 

unfortunately the Ant+ id cannot be read out from the Polar HRM.
