### ISSUE TITLE
Polar Verity Sense and Cassia BLE Hub

### ISSUE THREAD

**Issue by thebeard-lifebell** [polarofficial/polar-ble-sdk#291]
***Platform your question concerns:*** 
- [ ] Android 
- [ ] iOS
- [ x] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [ x] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

I am using a [Cassia](https://github.com/CassiaNetworks/CassiaSDKGuide/wiki/RESTful-API) Bluetooth Hub to connect with my Polar Verity Sense. And have been following [this](https://github.com/polarofficial/polar-ble-sdk/blob/master/technical_documentation/Polar_Measurement_Data_Specification.pdf) data specification sheet.

I followed the Prerequisite instructions (Indicate on CP, Notify on PMD Data)
I'm able to pair and Read Features (by reading the Control Point characteristic - the response is: 0F6E020000000000000000000000000000), but I'm not able to Request Stream Settings for PPG (by sending 0101 to the CP Characteristic). I feel like I'm missing more detailed documentation (don't know all the fields values in the Stream Settings response etc.).

Can someone please point me in the right direction, or let me know which pieces of information can help elucidate my problem?

P.S. Happy to provide the values of any descriptors or characteristics.

**Comment by JOikarinen** [comment]
Hi @thebeard-lifebell,

Unfortunately, we are only able to support Android and iOS. The SDK includes source code and you can feel free to utilize / port the code in other platforms too but that is something we are not able to provide support for.

There are earlier discussions which can help you, e.g.
https://github.com/polarofficial/polar-ble-sdk/issues/249#issuecomment-1064798244
