### ISSUE TITLE
How to parse acc delta frame?

### ISSUE THREAD

**Issue by ranjitIN** [polarofficial/polar-ble-sdk#294]
***Platform your question concerns:*** 
- [x] Platform is not relevant for this question

***Device:***
- [x] Polar Verity Sense

**Description:**

When I parse the raw value according the documentation 

The 1st bit represent : 02 
Time stamp :1 - 8
Frame : 9 which value is 128

**Comment by ranjitIN** [comment]
![image](https://user-images.githubusercontent.com/78366707/185735070-b1de3b97-1484-44e2-bb5a-3284df0b3b8c.png)

My question is how to convert these values in actual value

**Comment by JOikarinen** [comment]
Hi @ranjitIN, 

unfortunately, we are only able to support Android and iOS. The SDK includes source code and you can feel free to utilize / port the code in other platforms too but that is something we are not able to provide support for.

**Comment by ranjitIN** [comment]
Thanks 👍
