### ISSUE TITLE
Where is the Polar Feature Configuration Service (PFC) documented?

### ISSUE THREAD

**Issue by stuartlynne** [polarofficial/polar-ble-sdk#296]
I am working in Python/Bleak to develop a BLE app supporting the Polar H10 for PPI, PPG, and ECG data.

Is there any documentation on how to use the Polar Feature Configuration Service?

I would like to be able to do some of the features on and off, e.g. enable multi-channel, and/or disable Ant+. 

I can read the PFC_FEATURE characteristic successfully. 

But cannot read or write to the PFC_CP characteristic.

**Comment by JOikarinen** [comment]
Hi @stuartlynne,

I understand your question. Unfortunately the PFC service documentation is not publicly available. As you found out the PFC client code is open sourced within the SDK and you may investigate the behaviour. However we are not able support you on that at this moment.
