### ISSUE TITLE
No ECG in polarsdkecghrdemo

### ISSUE THREAD

**Issue by Je-Ho** [polarofficial/polar-ble-sdk#3]
I'm trying the demo app polarsdkecghrdemo with a Polar H10 - connection works, HR is shown but ECG is not shown. Logcat does not show ECG either, only HR. Should it work with an H10? 

![Screenshot_20190323-215432](https://user-images.githubusercontent.com/7677889/54871654-0c77a680-4db8-11e9-9938-95d3e4e81174.png)

**Comment by erkki-silvola** [comment]
You most likely don't have the version from H10 which supports ecg streaming.

**Comment by Je-Ho** [comment]
Thank you, I bought the sensor a few weeks ago and there is no firmware update higher than my installed version 2.1.9, so I didn't think about that 😉. Will it work with a future firmware update or is there a hardware update as well? Thanks again for making the SDK available!

**Comment by erkki-silvola** [comment]
There will be update later for H10.

**Comment by KennethEvans** [comment]
I have the same issue,  The PolarSdk-Exercise-Demo doesn't do anything either, just sits there.  Doesn't even display the HR.  After looking around I am not finding any real documentation on the SDK, apart from the Javadoc, which is pretty terse.  There is a Gatt spec and a DOCX that says the H10 does ECG with a sample rate of 130 Hz.  These aren't much help in understanding the SDK.

I also have version 2.1.9 on the H10.  What I read is that Polar beat will notify me when there is an update.  I am not seeing much use for the SDK as is.  Is this update coming soon?

**Comment by erkki-silvola** [comment]
The update will be available soon.

**Comment by Je-Ho** [comment]
Nice, the update is working, thanks!

**Comment by KennethEvans** [comment]
It's been 8 days since the response above, indicating the update is out.  However, I have not got an update notice for my H10.  My understanding is it will show up in Polar Beat.  Am I missing something?

Is there a manual way to get it?

**Comment by KennethEvans** [comment]
Apparently it came out yesterday (April 23). I just got it and am now getting ECG.
