### ISSUE TITLE
rrs and rrsMS what is the difference?

### ISSUE THREAD

**Issue by Winson-Foo** [polarofficial/polar-ble-sdk#301]
***Platform your question concerns:*** 
- [ X] Android 
- [ ] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [ ] Polar Verity Sense
- [ X] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**
Hello, I cannot seem to find any documentation regarding the difference between rrs and rrsMS? Why is the value slightly different?

**Comment by JOikarinen** [comment]
rrsMs: is the R to R peak in milliseconds 
rrs: the value how the rrs is delivered over Bluetooth. Bluetooth specification defines the resolution of RR-Intervals is 1⁄1024 seconds. rrsMs is just more user friendly representation of rrs.
