### ISSUE TITLE
what is the PPI sampling rate/frequency? 

### ISSUE THREAD

**Issue by flyindutche** [polarofficial/polar-ble-sdk#308]
***Platform your question concerns:*** 
- [ yes] Android 
- [ yes] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ yes] Polar OH1
- [ ] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**
I am using Polar OH1 and sdk to get PPG, PPI and HR etc data. While it seems the frequency of PPG data is usually stable- around 135hz, I am not sure what is the frequency of PPI and HR supposed to be. Are they supposed to change over time? I can't find in the document stating what is the frequency. I am trying to use PPI to calculate the HRV.

**Comment by JOikarinen** [comment]
Hi @flyindutche,

I understand your question. First the heart rate, the heart rate unit is beats per minute (bpm). It is difficult to define any sampling rate or timestamps for it. However, BLE specification states that heart rate sensor shall sent updated value once per second. You may check the [BLE specification](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.bluetooth.com%2Fspecifications%2Fspecs%2Fheart-rate-service-1-0%2F&data=05%7C01%7C%7C20d58848ddf243da663008da9bfda6e0%7C09970edaa4a64890a2e2cc2ac3a2ba32%7C0%7C0%7C637993811740707022%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VySfjG1oi%2F42zD5ppQ3tsnY35ADotZ1zyyOMUtZ1QZA%3D&reserved=0). 

And if we think of the peak-to-peak interval (PPI). It doesn't have frequency either, it is time between each pulse. By listening the PPI stream you will get continuous stream of PPI values detect by the OH1. From PPI values you can calculate the heart-rate-variability (HRV). I don't know is there any standard how the HRV is calculated, like what is time period you use to measure the variability. I guess the time period is decided by you best matching your use case.
