### ISSUE TITLE
Timestamps in PolarEcgData Data vs PolarHrData

### ISSUE THREAD

**Issue by wokremse** [polarofficial/polar-ble-sdk#31]
Hello Polar Team,

I am simultaniously acquiring ECG Data via Stream and HR Data via notifications. I would like them to both use the same timeline (ie timestamp format). However, I cannot figure out the format of `polarEcgData.timeStamp`. The documentation says it's nanoseconds, but nanoseconds starting from when?

Furthermore, is there any way of getting the time at which the HR data was generated on the sensor. I'd like to do something like `PolarHrData.timeStamp`.

Thank you and best regards

**Comment by erkki-silvola** [comment]
Hi,

The default epoch for H10 is 1.1.2000 , this can be changed through setLocalTime api( polarFileTransfer feature is needed for this ). Getting the time for HR notification is not available as it is not in the standard hr notification.
