### ISSUE TITLE
Verity Sense: using for running/sports data like ground contact, oscillation

### ISSUE THREAD

**Issue by CodezPoet** [polarofficial/polar-ble-sdk#310]
***Platform your question concerns:*** 
- [ ] Android 
- [ ] iOS
- [ ] Other
- [ x] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [ x] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**

TLDR My question:

Can the data pulled from the Verity be analyzed to the point of making sense  for sports analysis?  E.g. can consistently and accurately be told for ground contact with running or whether an arm is going forward, up, or down and with what force? 

Summary:

Considering coding an open source application (web based) , that can analyze movement data for running.
Similar to the Garmin Dynamic Running Pod or Trickr X. E.g. ground contact, oscillation, maybe balance. 

To place the Verity at the small of the back or below the navel, for a central point on the body maybe. Alternatively wear multiple sensors for arms, hip, and legs for example, and to use those metrics for sports like cycling, kickboxing, running, swimming. 

I did some testing with the Polar Sensor App by Jukka Haponen for example (since it provides save files for all the data maybe), and I can track movements for example.

My concern is if it is placed at the small of the back if things like ground contact can be analyzed? I mean this is similar to what the Garmin Tri and Trickr X hr bands do maybe? 

This is kind of what I envisioned when I first purchased the Verity. However the lack of apps for this, afaik, tells me this may be more complicated and frustrating than the marketing speak let's on? 

I am surprised polar isn't developing this more? Would seem to me there is a market for it. Again worries me that it may be trickier than at first glance, at present. Or they may be working hard on it, and releasing something, which would make coding for me "useless"

Before I land in coding hell with no reliable results, asking here since I see skilled and experienced people in this section

**Comment by JOikarinen** [comment]
Hi @CodezPoet, good thinking. 

Polar BLE SDK provides the data from different Polar sensors, VeritySense, OH1 and H10. The data provided is mostly raw, but also some processed data is available. 

By "raw" I mean the data is not manipulated anyhow, it just streamed from the Polar device as it is sampled by built in sensor. The processed data though goes through built in algorithms and more sophisticated data is got as output. 

For example the VeritySense provides raw ACC, Gyro, Magnetometer and PPG data. The processed data from VeritySense are HeartRate and Peak-to-peak interval (PPI).

In your described use cases you probably need some kind of motion detection to be processed from the raw data, maybe using acc, gyro and magnetometer data. At the moment there are no concrete plans the Polar would develop the motion detection or movement detection processing which then would be delivered via SDK for 3rd party developers.
