### ISSUE TITLE
Android app connecting to 2 Polar devices: H10 and Verity Sense

### ISSUE THREAD

**Issue by PaolaDF** [polarofficial/polar-ble-sdk#324]
***Platform your question concerns:*** 
- [X] Android 
- [ ] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [X] Polar Verity Sense
- [X] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**
I am developing an app based on the Polar SDK where I connect an android phone to the Polar H10 and save the data. 
I want to add a Verity Sense to my setup in order to also have the PPG. 
Is it possible to establish 2 connections (the app connects to 2 Polar devices) through the Polar APIs?

**Comment by JOikarinen** [comment]
Hi @PaolaDF, it is totally possible. Each of API function (which is relative to device) takes the device identifier as parameter. You may establish the connection as many devices you wish, the SDK is not limiting the amount of parallel connection.

You just call the connection for all the devices you want, i.e. `api.connectToDevice(<identifier>)`
