### ISSUE TITLE
I have a new kind of extrasystole.  This has never happened before, is this normal?

### ISSUE THREAD

**Issue by ivgi1** [polarofficial/polar-ble-sdk#328]
***Platform your question concerns:*** 
- [* ] Android 
- [ ] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [ ] Polar Verity Sense
- [ *
![Screenshot_20230210-100101](https://user-images.githubusercontent.com/124996262/218035502-75f06398-ac0f-48b6-91e5-b9638ba0cf97.png)
![Screenshot_20230203-073236](https://user-images.githubusercontent.com/124996262/218035580-219023eb-71c0-4253-97eb-1c3becadb08e.png)
] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**
Hello.  I have been suffering from extrasystole for several months now.  but it's something new and I don't know if it's normal.  I will be grateful for help.

**Comment by andYgnite** [comment]
Hello @ivgi1 

I am sorry to hear that you've been experiencing extrasystole. It's essential to consult with a qualified healthcare professional who can properly evaluate your symptoms and provide appropriate guidance.

Take care and stay healthy!
