### ISSUE TITLE
iOS and Android SDK inconsistencies

### ISSUE THREAD

**Issue by Rexios80** [polarofficial/polar-ble-sdk#329]
This isn't a bug, but an inconsistency between the iOS and Android SDKs in the latest `5.0.0-beta2`.

iOS:
<img width="1126" alt="Screenshot 2023-02-13 at 12 56 56 PM" src="https://user-images.githubusercontent.com/7896519/218535651-797ed3fc-83c4-40c9-8570-6e5ac5094867.png">

Android:
<img width="704" alt="Screenshot 2023-02-13 at 12 57 10 PM" src="https://user-images.githubusercontent.com/7896519/218535702-5e921860-f37b-4d13-a62a-70a51b392354.png">

Ideally, these should be the same, and match the structure of the other streaming features data types

**Comment by Rexios80** [comment]
Also shouldn't `PolarHrSample` have a timestamp field?

**Comment by Rexios80** [comment]
Another inconsistency I've noticed is `PolarOhrPpi` related names

iOS:
- `PolarPpiData`
- `startOhrPpiStreaming`

Android:
- `PolarOhrPPIData`
- `PolarOhrPPISample`
- `startOhrPPIStreaming`

I think these names would be more consistent considering the names of other features:
- `PolarPpiData`
- `PolarPpiSample`
- `startPpiStreaming`

**Comment by JOikarinen** [comment]
Thanks for the feedback @Rexios80. Here is the PR of your suggestion #345

**Comment by Rexios80** [comment]
Closing. Thanks for fixing this.
