### ISSUE TITLE
Cannot enable notification on PMD Data MTU Characteristic

### ISSUE THREAD

**Issue by dumbshow** [polarofficial/polar-ble-sdk#33]
Hi, I'm having trouble executing the "Prerequisite" listed on page 2 of the "Polar Measurement Data Specification for 3rd Party."  I'm using gatttool, as shown below.  But I cannot enable notification on the PMD Data MTU Characteristic (handle: 0x004a, uuid: fb005c82-02e7-f387-1cad-8acd2d8df0c8).  Any help would be truly appreciated.  Thanks.

```
$ gatttool -t random --device=DE:38:8F:EE:D0:08 --interactive --mtu=232

[DE:38:8F:EE:D0:08][LE]> connect
Attempting to connect to DE:38:8F:EE:D0:08
Connection successful
[DE:38:8F:EE:D0:08][LE]> char-write-req 0x0047 0200
Characteristic value was written successfully
[DE:38:8F:EE:D0:08][LE]> mtu 232
MTU was exchanged successfully: 232
[DE:38:8F:EE:D0:08][LE]> char-write-req 0x004a 0100
Error: Characteristic Write Request failed: Attribute can't be written
```

**Comment by erkki-silvola** [comment]
Hi,

You are writing to wrong att handle.

**Comment by dumbshow** [comment]
Thank you
