### ISSUE TITLE
Possible to download accelerometer on Polar Verity Sense after 24 hours?

### ISSUE THREAD

**Issue by RealLast** [polarofficial/polar-ble-sdk#337]
***Platform your question concerns:*** 
- [x] Android 
- [ ] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [x] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**

Hello,

we would like to use the Polar Verity Sense in a study where we measure accelerometer data over 24 hours. As far as we understood, accelerometer data can be transmitted live when a bluetooth connection is available. However, this means that for continuous measurements, the mobile phone always has to be within reach of the Polar. This is not feasible for us, since we can not guarantee that participants will always have their phone with them.

Is it possible to use this SDK to record accelerometer data locally over 24 hours and download it afterward? Alternatively, it would also be an option to download data in shorter intervals, such as every 6 hours, if the internal memory of the Polar is not big enough to store data for 24 hours.

Thank you very much.

Best regards

**Comment by JOikarinen** [comment]
Hi @RealLast, sorry for delayed reply. 

> Is it possible to use this SDK to record accelerometer data locally over 24 hours and download it afterward?

The latest[ beta version](https://github.com/polarofficial/polar-ble-sdk/releases/tag/5.0.0-beta4) of the SDK allows for offline recording directly to the Polar Verity Sense device memory, eliminating the need for continuous BLE streaming. You can learn more about offline recording in the documentation, available at this link: https://github.com/polarofficial/polar-ble-sdk/blob/polar-ble-sdk-5.0.0/documentation/OfflineRecordingExplained.md 

> Alternatively, it would also be an option to download data in shorter intervals, such as every 6 hours, if the internal memory of the Polar is not big enough to store data for 24 hours.

The VeritySense device has 13.7MB of memory available for offline recordings. Assuming previously saved recordings have been removed from the device's memory, it can accommodate 24 hours of ACC data sampled at 26Hz. The Verity Sense compresses the offline recording data very effectively. The compression rate however depends on various factors. However, it is possible to calculate worst-case scenarios. For instance, if data is sampled at 52Hz, VeritySense can store at least 12 hours of ACC data, and if sampled at 26Hz, at least 23 hours of ACC data can be stored.

**Comment by padre9027-ship-it** [comment]
Hello, is it possible to access accelerometer and gyroscope data from the Polar Verity Sense? I managed to have access to HR but not the other sensors. I also managed to have access to accelerometer data using the H10 strap, but I wanted to use the Polar Verity Sense too. I am not really coding this; I am asking Google AI Studio to develop the application for me. Thank you!
