### ISSUE TITLE
Cannot get PPI that is over 20minutes

### ISSUE THREAD

**Issue by rikuriver0** [polarofficial/polar-ble-sdk#34]
I am trying to get PPI from OH1(firmware2.0.11).But I can get  only 20 minutes PPI.
Is this due to internal logic of OH1? If it is not so, Do you have any idea about this problem?
There are no error in my logcat and other data(HR) continue being got.

**Comment by erkki-silvola** [comment]
One reason could be if there is too much movement which should raise PolarOhrPPIData.blockerBit

**Comment by rikuriver0** [comment]
Thanks for fast reply.
I get PPI every 5seconds and returned value of blockerBit is always false. but it starts streaming and stops 20minutes later.
If the reason is that,how to get long time data?

**Comment by erkki-silvola** [comment]
Hi,

We found out that this is an issue in OH1 firmware, and until this is fixed as a workaround you can try restarting PPI measurement after every 20mins?

**Comment by rikuriver0** [comment]
I hava already tried restarting PPI measurement and I succeeded to get PPI more than 20mins.
But there is a problem. it takes 20seconds until restart. The blank data which is caused by restart is important for us.
I hope that firmware issue is fixed in the near future.
Thank you for having you tell me a cause.
