### ISSUE TITLE
Does this sdk works for Polar watches?

### ISSUE THREAD

**Issue by lsl-88** [polarofficial/polar-ble-sdk#340]
***Platform your question concerns:*** 
- [x] Android 
- [ ] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [ ] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [x] Other
- [ ] Device is not relevant for this question

**Description:**

Hello,

I would like to check if the sdk works for Polar smart watches, for instance Polar Ignite 2 or Polar Ignite 3. Thanks.

**Comment by JOikarinen** [comment]
Hi @lsl-88, 

the SDK is not working with Polar smart watches, only with the sensors like H10, H9 and VeritySense
