### ISSUE TITLE
Device Disconnected on startOhrPPIStreaming

### ISSUE THREAD

**Issue by muammar-yacoob** [polarofficial/polar-ble-sdk#341]
**Platform on which you observed the bug:** 
- [x] Android 
- [ ] iOS
- [ ] Other
- [ ] Platform is not relevant for this bug

**Device on which you observed the bug:**
- [ ] Polar OH1
- [x] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this bug

**Device Disconnects on `PolarBleApi.startOhrPPIStreaming`**
On Verity Sense, right after calling `api.startOhrPPIStreaming()` I get this error
` com.polar.sdk.api.errors.PolarDeviceDisconnected`

Also when attempting to reconnect using `api.connectToDevice(deviceId)` I get this error:
![image](https://user-images.githubusercontent.com/8532589/224034637-69ac130a-0cb3-45ab-9676-0837d8f55538.png)

Please advise.

**Comment by JOikarinen** [comment]
Hi @muammar-yacoob, could you explain in more details that in which conditions you face the problem? Have you tried with the example app: https://github.com/polarofficial/polar-ble-sdk/tree/master/examples/example-android/androidBleSdkTestApp
