### ISSUE TITLE
How many data types can be streamed simultaneously?

### ISSUE THREAD

**Issue by PaolaDF** [polarofficial/polar-ble-sdk#342]
***Platform your question concerns:*** 
- [X] Android 
- [ ] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [X] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**
How many data types can be streamed simultaneously?

Polar verity sense provides 5 data types:
• Accelerometer
• Gyroscope
• Magnetometer
• PPG
• PPI

Questions:
1. Can all of them be streamed at the same time? 
2. Is there a limit on the number of data types streamed simultaneously? What does it depend on?
Consider the Android smartphone fitting in the requirements specified on the Polar website.

**Comment by JOikarinen** [comment]
Hi @PaolaDF, 

> 1. Can all of them be streamed at the same time?

Yes they can. 

> 2\. Is there a limit on the number of data types streamed simultaneously? What does it depend on?

The limiting factor is BLE throughput. If you go to extreme with sampling rates the data will start to drop. I did quick testing with on Android phone and asked the following streams: ACC(52Hz), PPG (55Hz), PPI, MAG (10Hz), GYR (52Hz). With this quick test no data was lost in 10 minutes test.
