### ISSUE TITLE
Command to set polar H10 local time.

### ISSUE THREAD

**Issue by Arthur-HITLab** [polarofficial/polar-ble-sdk#349]
***Platform your question concerns:*** 
- [x] Other

***Device:***
- [x] Polar H10

**Description:**
I'm working on a python project to read the ECG data. I'm looking for a way to set the local time using a byte array since I cant use the SDK in python. So far I can connect to the polar and read the ECG stream, but the commands to read or set the time don't work. The polar doesn't respond in any way. The command I tried was [0x02, 0x00, 0x00, 0x80] which I got from the SDK source code. I also tried to enable SDK mode on the polar by sending [0x02, 0x09], the H10 responded with [0x0f, 0x05, 0x00, 0x00, 0x00,...]. According to the docs this means that there is an invalid parameter?

**Comment by JOikarinen** [comment]
@Arthur-HITLab,

Unfortunately we are only able to support Android and iOS. The SDK includes source code and you can feel free to utilize / port the code in other platforms too but that is something we are not able to provide support for.
