### ISSUE TITLE
Timestamp in PolarHrData

### ISSUE THREAD

**Issue by qerlly** [polarofficial/polar-ble-sdk#356]
***Platform your question concerns:*** 
- [ ] Android 
- [ ] iOS
- [ ] Other
- [x] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [ ] Polar Verity Sense
- [x] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**
Is it possible to add timestamp to PolarHrData? If you made the logic of streaming PolarHrData the same as PolarEcgData and PolarAccelerometerData, why do they have a timestamp and PolarHrData does not?

**Comment by samulimaa** [comment]
Hello, good question.

Reason why PolarHrData does not contain timestamp is due to fact that timestamps are not part of the [BLE Heart Rate Service GATT specification](https://www.bluetooth.org/docman/handlers/downloaddoc.ashx?doc_id=239866):

> 
>     3.4 Requirements for Time-Sensitive Data
> 
>     The Heart Rate Measurement characteristic contains time sensitive data and is considered a time-sensitive characteristic, thus the following requirements apply:
> 
>     Since this service does not provide for a time stamp to identify the measurement time (and age) of the data, the value of the Heart Rate Measurement characteristic shall be discarded if either the connection does not get established or if the notification is not successfully sent to the Client (e.g., link loss).
