### ISSUE TITLE
Is it possible to store Accelerometer Data on H10?

### ISSUE THREAD

**Issue by abbjetmus** [polarofficial/polar-ble-sdk#357]
***Platform your question concerns:*** 
- [ ] Android 
- [ ] iOS
- [ ] Other
- [ X] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [ X] Polar Verity Sense
- [ X] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

Is it possible to store Accelerometer Data as well as HR/RR Data offline on the sensor memory when using Polar H10 or is it just possible with Polar Verity Sense? We would like to have a seamless connection, when going from online to offline measuring of HR, RR and Accelerometer. If sensor is connected to app reading should be through ble and if user puts the phone in locker room measurement should continue on sensor and after automatically connect and  sent to database and continue with ble, Is this possible with Polar Verity Sense?

**Comment by samulimaa** [comment]
Hi, SDK does not support offline recording of accelerometer data with Polar H10.
You can use Polar Verity Sense offline recording to record HR/accelerometer data. Note that Verity Sense uses optical heart rate measurement, so RR data is not available.
