### ISSUE TITLE
SDK on macOS

### ISSUE THREAD

**Issue by mpepito13** [polarofficial/polar-ble-sdk#358]
***Platform your question concerns:*** 
- [ ] Android 
- [ ] iOS
- [x ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [ ] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ x] Device is not relevant for this question

**Description:**

Hello,

I would like to know why the SDK is mobile only ? 
Is there any plan to port it to macOS ?

Thanks

**Comment by samulimaa** [comment]
Hello, unfortunately, there are currently no plans to port SDK to new platforms such as macOS.

**Comment by jimmyzumthurm** [comment]
Hi @mpepito13 , 
It is difficult to judge. There are people that already did porting to other platforms and languages (), but having no experience in MacOS application development I cannot say. We do not have the resources to support the SDK on other platforms than Android and iOS for now, so unfortunately support with remain on those 2 platforms only for now.
