### ISSUE TITLE
Verity Delta Sample Timestamps

### ISSUE THREAD

**Issue by fagerbur** [polarofficial/polar-ble-sdk#361]
Platform your question concerns:

- [ ] Android
- [ ] iOS
- [X] Other
- [ ] Platform is not relevant for this question

Device:

- [ ] Polar OH1
- [X] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

Description:
Hello, there was a technical spec document in the repo that was recently removed [Polar Measurement Spec](https://github.com/polarofficial/polar-ble-sdk/blob/39c809ab4a3398d3ea88ff8a0cc6f6d44cd58bda/technical_documentation/Polar_Measurement_Data_Specification.pdf) for the 5.0.0 release. I have code written that parses the ACC and PPG data streams from the Verity and I recently updated my firmware and realized that v4.0.0 introduced timestamps with each delta sample. Will that document be updated to show the inclusion of the timestamps? If not, is the timestamp that has been added to the delta samples a delta from the original timestamp just like the ACC and PPG delta samples are from the reference? The 4.0.0 release notes seemed to show that it was a long but I wasn't sure if that was just the reference sample or the delta samples.

**Comment by jimmyzumthurm** [comment]
Hi @fagerbur 

I can't really answer related to the documentation, but the time-stamping of individual samples follows the same logic for each measurement type that has timestamps: 

- On device side, raw sensor data is received and compressed into what we call a **delta frame**. When a **delta frame** reaches connection MTU size, it will set the timestamp of that delta frame to the timestamp of the **last sample** in it, and sent it to Polar SDK client. 
- Polar SDK client receives these delta frames, 1 by 1. How it calculates the timestamp of each individual samples is like that : 

```
x = current_delta_frame.timestamp - prev_delta_frame_timestamp;
y = x / current_delta_frame.nb_samples
for i, sample in enumerate(current_delta_frame) : 
    sample.timestamp = prev_delta_frame_timestamp + i * y
```

For the first received delta frame, logic is different has `x `delta between frames cannot be calculated yet. It will use this formula instead, using the frame timestamp and the sample rate : 
```
y = current_delta_frame.nb_samples / current_delta_frame.sample_rate
for i, sample in enumerate(current_delta_frame) : 
    sample.timestamp = current_delta_frame.timestamp - (current_delta_frame.nb_samples - i)*y
```

I hope this clarifies your questions.
