### ISSUE TITLE
PPG Curve Pattern

### ISSUE THREAD

**Issue by beatrizbonafini** [polarofficial/polar-ble-sdk#367]
***Platform your question concerns:*** 
- [ ] Android 
- [ ] iOS
- [ ] Other
- [x] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [x] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**

The ppg curve has a pattern that describes the heartbeat frequency and consequently the modulations generated by the blood volume. Usually, there are other patterns observed in the PPG curve: RIAV, RIIV and RIFV,  as the figure is shown below.

![image](https://github.com/polarofficial/polar-ble-sdk/assets/1916311/57ff3cd6-cce3-44d8-953e-a9037ac829c0)

Image source: https://europepmc.org/article/pmc/pmc5175543

Using the polar device, we are trying to correlate the real data and value captured by the sensor, but the data of modulation RIAV, RIIV and RIFV is not matching with the real. **My question is about the support that the sensor gives to describe these modulations. Is there any problem related to this?** It is possible to notice the curve pattern of these modulations, but the results have a huge delay.

**Comment by andYgnite** [comment]
Hi @beatrizbonafini,
Can you please details more how do you get raw PPG data?
Verity Sense is used in several research studies and you should be able to see RIFV, RIIV and RIAV modulations.
