### ISSUE TITLE
Swift 5.1 support

### ISSUE THREAD

**Issue by ilm3** [polarofficial/polar-ble-sdk#37]
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler

**Comment by erkki-silvola** [comment]
Hi, I will update the SDK for the latest toolchain this week...

**Comment by RGreinacher** [comment]
Hey Erkki, any chance you can provide the update by today? That'd be fantastic!

**Comment by dasdranagon** [comment]
Agreed! Would be good to have an update today. Or at least a realistic estimate.

**Comment by RGreinacher** [comment]
Thank you @erkki-silvola! Your patch works like a charm!
