### ISSUE TITLE
On SDK Mode listOfflineRecordings does not work

### ISSUE THREAD

**Issue by merschel** [polarofficial/polar-ble-sdk#374]
**Platform on which you observed the bug:** 
- [ ] Android 
- [x] iOS
- [ ] Other
- [ ] Platform is not relevant for this bug

**Device on which you observed the bug:**
- [ ] Polar OH1
- [x] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this bug

**Describe the bug**

Hi,

On SDK mode the function listOfflineRecordings response always in responseError(errorCode: 202).

In the normal mode listOfflineRecordings works fine.

Verty Sense Firmware is 2.1.0
SDK Version is 5.1.0

**Comment by jimmyzumthurm** [comment]
Hi @merschel  

Error 202 is telling me that you are trying to read or list the files from one of those 3 states : 

1) Device was booted in exercise mode (also called internal recording). You would need to reboot your device in sensor mode (the "heart")
2) Device was booted in swim mode. Same as 1)
3) SDK mode is enabled. Currently you need to disable SDK mode to be able to get your files. 

We will add documentation to explain better these limitations. Note that the first 2 will probably remain like that, but we will discuss internally if we could allow syncing of files from SDK mode.

**Comment by jimmyzumthurm** [comment]
@merschel I agree with you that is not intuitive and also missing from documentation, that will be added. These is historical reason for that block, which may not be valid anymore since we introduced the offline recording feature.

**Comment by jimmyzumthurm** [comment]
@merschel FYI, in next release (can't give any ETA yet), it will be possible to fetch recordings from SDK mode. 

Also note that there is similar "SYSTEM BUSY" block when device is in exercise mode / swim mode. Unfortunately these blocks will need to remain, because this is needed to prevent sync with Flow service during exercise
