### ISSUE TITLE
I am going to add Polar SDK to the vr project of unity3d

### ISSUE THREAD

**Issue by BNUZ-HuSir** [polarofficial/polar-ble-sdk#376]
***Platform your question concerns:*** 
- [√] Android 
- [ ] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [√] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**
I am a beginner. I am going to add Polar SDK to the vr project of unity3d. Is it feasible to realize it?

**Comment by jimmyzumthurm** [comment]
As a beginner you might need to familiarize yourself with SDK documentation and Unity development processes.
However with some effort and learning, you should be able to achieve it.

We cannot provide much help on the subject though
