### ISSUE TITLE
PPI timestamp property always reported as 0. (Polar iOS Demo app with OH1)

### ISSUE THREAD

**Issue by marchv** [polarofficial/polar-ble-sdk#38]
Hi Polar team :)

I have just updated my OH1 to latest firmware and downloaded your iOS-SDK. I then wanted to get PPI samples and added some prints in the ppiToggle(_ sender:) method:

```
                case .next(let data):
                    print("data timestamp: \(data.timeStamp)") // always zero!
                    for item in data.samples {
                        NSLog("PPI: \(item.ppInMs); errorEstimate: \(item.ppErrorEstimate)")
                    }
```

But 'date.timestamp' is always zero!?

Or have I misunderstood the interface?

I also tried to call setTime (succeeded) once connected but that made no difference...

The reason for this is that I wanted to try to export the Beat-To-Beat-Interval to Apple's HealthKit (iOS 13). But maybe this is not possible...

Update: I do get timestamp for Acc. and PPG samples. So it seems to be a problem for PPI only.

Thanks!

**Comment by erkki-silvola** [comment]
Hi,

We found issue in OH1 firmware regarding ppi timestamps...

**Comment by FloNOC** [comment]
Hi,

The whole documentation seems to indicate that the timestamp for OH1 PPI will always be 0.

So is it a bug or a feature ? ;-)

**Comment by erkki-silvola** [comment]
It is a bug in OH1, and it seems that it cannot be even fixed

**Comment by FloNOC** [comment]
Oh, ok.

I thought it was linked with the fact that the OH1 seems not to have a "clock", as there is no way to set it throught BLE, is it ?

**Comment by erkki-silvola** [comment]
There is epoch on the OH1, it is just an internal software structure which affects that there is no way to add accurate timestamp for ppi

**Comment by FloNOC** [comment]
Oh, OK.

Thanks for the info, we'll keep on using the reception device's timestamp then.

**Comment by marchv** [comment]
@erkki-silvola thanks for being open about the problem in OH1 👍
