### ISSUE TITLE
Some information on Heart Rate Variability Values

### ISSUE THREAD

**Issue by gd1925** [polarofficial/polar-ble-sdk#384]
***Platform your question concerns:*** 
- [ ] Android 
- [ ] iOS
- [ ] Other
- [x] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [ ] Polar Verity Sense
- [x] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**

Hi everyone,

I wanted to know - what is the normal range of HRV? Some I tend to see the value in 2 digits and sometimes the values are 1000+. I am bit confused on what the ideal range should be. Can a value of 400-500 be considered a valid HRV value? Thank you.

**Comment by erikboto** [comment]
There are a lot of various metric that can fall under the umbrella term "HRV", and I'm unsure what you are referring to in your question. From the Polar H10 you will not get any HRV values, but you can get the RR-intervals (basically the time between heart beats) which can then be recorded for a while to calculate various HRV metrics.

If you are new to HRV I would suggest reading an article series from Marco Altini that gives a good introduction: https://medium.com/@altini_marco/the-ultimate-guide-to-heart-rate-variability-hrv-part-1-70a0a392fff4
