### ISSUE TITLE
How to get RR values from polar verity sense using polar ble sdk

### ISSUE THREAD

**Issue by RitikaNigam-ux** [polarofficial/polar-ble-sdk#386]
***Platform your question concerns:*** 
- [o] Android 
- [ ] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [o] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**
I have connected the polar verity sense with the polar ble sdk but when I click on start HR stream button on polar ble sdk app. I do get HR (bpm) data but I am not getting rr value. How do I stream rr values for polar verity sense using polar ble sdk app?
<img width="1117" alt="Screenshot 2023-07-13 at 4 50 48 PM" src="https://github.com/polarofficial/polar-ble-sdk/assets/73180903/a2e2a2af-b4d3-4152-affd-61be1fc173f8">

**Comment by jimmyzumthurm** [comment]
Hi, RR is the interval between two R-peaks : 
![B4j77](https://github.com/polarofficial/polar-ble-sdk/assets/62651430/4cd39f33-6de3-489b-9499-a9518125bc30)
That is something specific can only be measured with ECG (strap based sensors like H9,H10). 

Verity Sense is a PPG based sensor so RR interval is not available. You can get PP intervals which is a similar beat-to-beat representation, this [article ](https://www.researchgate.net/publication/331227748_Compatibility_of_pulse-pulse_intervals_with_R-R_intervals_in_assessing_cardiac_autonomic_function_and_its_relation_to_risks_of_atherosclerosis) talks about these 2 more in detail. For that you need to use `startPpiStreaming()` API
