### ISSUE TITLE
Commands BLE Documentation (send and receive bytes frames)

### ISSUE THREAD

**Issue by Chakib-Temal** [polarofficial/polar-ble-sdk#400]
***Platform your question concerns:*** 
- [x] Android 
- [x] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [ ] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [x] Device is not relevant for this question

**Description:**

Hello,

I'm working on a Flutter (Mobile) project, I'm already using a BLE plugin to communicate with lots of other sensors.

I'd like to add Polar sensors to my list, but is there any clear documentation on how to communicate with the sensor, read the data (order and reception) ? 

1- Discover Polar Services and Features
2- How to streaming and Decoding Data 

Best regards,

**Comment by samulimaa** [comment]
Hello,

1- Available features depend on the Polar device you are using. Please see https://github.com/polarofficial/polar-ble-sdk#features for more information.

2- Streaming is started by calling the corresponding streaming functions such as `startHrStreaming()`, `startEcgStreaming()`, `startAccStreaming()`...
These functions provide Rx Flowable that emits values to your application. The SDK handles data decoding, before mentioned Rx Flowable has a data class as its type parameter, which contains decoded data. For example `startHrStreaming()` emits [PolarHrData](https://github.com/polarofficial/polar-ble-sdk/blob/master/sources/Android/android-communications/library/src/sdk/java/com/polar/sdk/api/model/PolarHrData.kt).

I also suggest taking look of [example apps code.](https://github.com/polarofficial/polar-ble-sdk/tree/master/examples)

Best regards,
Samuli
