### ISSUE TITLE
Swift 5.1.2 Support

### ISSUE THREAD

**Issue by ilm3** [polarofficial/polar-ble-sdk#41]
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler

**Comment by Narragansett** [comment]
Second that. Am now stuck. Please fix!

**Comment by erkki-silvola** [comment]
Yep, this will be handled today

**Comment by erkki-silvola** [comment]
iOS sdk and dependencies compiled with Xcode 11.2 are in master. Release tag will be done tomorrow.

**Comment by PranavBhatS** [comment]
is there any update on this? Still, I'm facing this issue.
