### ISSUE TITLE
PPI stream failed. Reason: com.polar.sdk.api.errors.PolarNotificationNotEnabled

### ISSUE THREAD

**Issue by vbheemr** [polarofficial/polar-ble-sdk#423]
***Platform your question concerns:*** 
- [ o] Android 
- [ ] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [ 0 ] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**
Coming to polar sensor reconnection ,I've encountered an issue during the sensor reconnection process. While the sensor successfully reconnects, the PPI stream values are not updating as expected after reconnecting.I wanted to know how to solve this error and enable PPI stream.

 The error message we're facing is:
 <img width="1440" alt="Screenshot 2023-12-01 at 9 26 57 AM" src="https://github.com/polarofficial/polar-ble-sdk/assets/137340019/b4a5ba34-0d07-46c7-968b-f3f1af1021c9">

**Comment by jimmyzumthurm** [comment]
hi @vbheemr , 
From your logs I see that you try to access the PMD service (FB005C80-02E7-F387-1CAD-8ACD2D8DF0C8) before subscribing to the characteristics (last 3 lines from your logs) that are needed to start PPI recording. In log after you see "Streaming feature XXXX is ready" which means after that only you will be able to restart the PPI recording. Maybe you could use that callback to restart PPI recording on re-connection ?

**Comment by jimmyzumthurm** [comment]
The callback to use seems to be  `bleSdkFeatureReady ` if you are using SDK 5.0.0 or later
