### ISSUE TITLE
Cannot get PPI for longer than 20 minutes

### ISSUE THREAD

**Issue by FloNOC** [polarofficial/polar-ble-sdk#43]
Hello,

It is the same issue as exposed here : https://github.com/polarofficial/polar-ble-sdk/issues/34
This issue is closed, but the problem still exists.

We have made a workaround in our application, but it results in having 20s gaps in measurements, which is very annoying...

As much as I know that it is a firmware issue, is it possible to use this one as a follow-up for when it's fixed ?
If not, just close it ;-)

Thank you

**Comment by erkki-silvola** [comment]
There will be a fix for this but I cannot promise any time schedule for this yet...

**Comment by pro-g111** [comment]
I am having the same issue as @FloNOC.

**Comment by FloNOC** [comment]
> There will be a fix for this but I cannot promise any time schedule for this yet...

Again, thank you for your work and the infos. In case this bug get fix in any way, please please update this issue, which I'll keep open for that purpose.

This one is pretty critical for us to use polar devices for our application.

**Comment by AmbroiseRecht** [comment]
We have the same issue and we are very interesting in the fix.

Any update about this ticket ?
Do you have news about a schedule for the fix ?

**Comment by erkki-silvola** [comment]
Hi, 

The fix is coming but no exact schedule yet available, I will inform later....

**Comment by erikboto** [comment]
Any news, good or bad?

**Comment by erkki-silvola** [comment]
Hi,

Fix has been already made but there is no schedule yet when release will be rolled out...

**Comment by AmbroiseRecht** [comment]
Hi,

Thank you for the information @erkki-silvola 
Do you have more information about the release date of this new firmware ?
Do you know if we will have just to update the firmware or if we will have to change the SDK also ?

**Comment by JOikarinen** [comment]
The [firmware 2.1.20](https://support.polar.com/en/updates/polar-oh1-firrmware-update-2120?product=OH1) to OH1 shall fix the problem
