### ISSUE TITLE
Polar Verity Sense device broadcast the Heart Rate even device does not touch the body.

### ISSUE THREAD

**Issue by DipakChhag149** [polarofficial/polar-ble-sdk#430]
***Platform your question concerns:*** 
- [ ] Android 

***Device:***
- [ ] Polar Verity Sense

**Description:**
We are working on a medical device android app, Which showing heart rate continuously after connection but we want to show the hear rate only if user has wear the device and sensor touch to user body. 
Now if we put polar device on desk and try to fetch the heart rate it broadcast continue instead 0

Please suggest the way to detect that user has wear the device or not.

**Comment by jimmyzumthurm** [comment]
Hi @DipakChhag149 , 
This is known limitation of the algorithm used in Verity Sense, that pulsing light coming through the optical front end could make device interprets it as skin contact and output HR different than 0 over the air even when device is not being worn. As there is no plans to fix that, I would say the only reliable way of knowing if the sensor is being worn is to stream accelerometer data using this SDK and make analysis of wear detection based on that.
