### ISSUE TITLE
SDK for the Polar Pacer Pro

### ISSUE THREAD

**Issue by lcossu** [polarofficial/polar-ble-sdk#436]
***Platform your question concerns:*** 
- [ ] Android 
- [ ] iOS
- [x] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [ ] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [x] Other
- [ ] Device is not relevant for this question

**Description:**
Hi, 
I have a Pacer Pro smartwatch and I have been trying to make it work with the SDK. I have seen that it is not listed among the compatible devices and currently, I'm not able to get any data from it. 

Are there any plans to extend the SDK to that smartwatch model too?
Thanks

**Comment by jimmyzumthurm** [comment]
Hi,

SDK support has been added as part of the 2.0 Pacer and Pacer Pro releases. See these steps to be able to stream the data : https://github.com/polarofficial/polar-ble-sdk/blob/master/documentation/UsingSDKWithWatches.md
