### ISSUE TITLE
cannot find symbol method autoConnectToPolarDevice

### ISSUE THREAD

**Issue by astralmedia** [polarofficial/polar-ble-sdk#44]
In my java class, I declare the variable:

`PolarBleApi api = PolarBleApiDefaultImpl.defaultImplementation(reactContext, PolarBleApi.FEATURE_HR);`

then in my method I hit later, I call autoConnect:

`api.autoConnectToPolarDevice(-50, null).subscribe();`

I just keep getting this error:

```PolarModule.java:70: error: cannot find symbol
        api.autoConnectToPolarDevice(-50, null).subscribe();
           ^
  symbol:   method autoConnectToPolarDevice(int,<null>)
  location: variable api of type PolarBleApi
1 error```

Thanks for any insight.

**Comment by erkki-silvola** [comment]
Hi,

It has been renamed a while ago to autoConnectToDevice

**Comment by astralmedia** [comment]
Thank you! FYI the Readme main android example has the old method.

**Comment by mohataher** [comment]
Please reconsider updating the README once again. The default signature is deprecated.

```
polarBleApi.autoConnectToDevice(-50, null); // cannot resolve method 
```

**Comment by JOikarinen** [comment]
@mohataher fixed in https://github.com/polarofficial/polar-ble-sdk/commit/40ae0c4d934a117b67f66e520510dbdea4e2fbd6.
