### ISSUE TITLE
Extract PP intervals with Matlab

### ISSUE THREAD

**Issue by Ax06** [polarofficial/polar-ble-sdk#441]
***Platform your question concerns:*** 
- Other (Matlab)

***Device:***
- Polar OH1

**Description:**

Hello,

I am currently working on an application using the Polar OH1 under the Matlab environment. I have successfully retrieved the heart rate data using the code snippet below, but I don't know how to extract the PP intervals for conducting HRV analyses. Do you know if this is possible with Matlab?

Thank you in advance for your assistance.

OH1 = ble(device_name)
hr = characteristic(OH1,'Heart Rate', Heart Rate Measurement');
data = read(HR)

**Comment by jimmyzumthurm** [comment]
Hi @Ax06 ,

PPI data is transferred over Polar proprietary BLE service that might not supported from MATLAB, so you would need to implement the service characteristics yourself to start the PPI streaming and subscribe to data. 

As Polar we only officially supports iOS and Android platforms with the SDK, so unfortunately we won't be able to support you with that, but if you would like to port such functionality to other platforms the Android/iOS code is open source and be ported to any platform.
