### ISSUE TITLE
Re-initialize PPI streaming

### ISSUE THREAD

**Issue by FloNOC** [polarofficial/polar-ble-sdk#45]
For a workaround for the 20min PPI stream limit (see issue #34 ), we've automatically reset the PPI streaming.

But very often, the PPI streaming does not restart; the light passes from flashing purple to flashing green, rather than passing flashing purple to flashing white (which the OH1 does at the beginning of a PPI stream); and no PPI value is ever sent.

The way we did is frankly abrupt: we just nullify the disposable, then relaunch the subscribe.

Is there a better, sure-shot way to reset it ?

Thank you.

**Comment by erkki-silvola** [comment]
hi,

sorry there is no proper way to do it...

**Comment by FloNOC** [comment]
Ok, thank you
