### ISSUE TITLE
PC-Support

### ISSUE THREAD

**Issue by fre4kyC0de** [polarofficial/polar-ble-sdk#46]
Is there any plan to add support for computers (Windows, Linux, ...)?

Currently I‘m using my own implementation to interpret the data using Bluetooth GATT (HeartRate). It would be great to get an official SDK, which would allow to view even more data (such as the ECG signal).

**Comment by jussivirkkala** [comment]
You can use https://github.com/polarofficial/polar-ble-sdk/blob/master/technical_documentation/Polar_Measurement_Data_Specification.pdf for additional data with own implementation

**Comment by willianpaixao** [comment]
Agreed, official SDK support for PC is a must feature.

**Comment by pablomainar** [comment]
Any news on this?

**Comment by JOikarinen** [comment]
At the moment this is our official statement: "Unfortunately, we are only able to support Android and iOS. The SDK includes source code and you can feel free to utilize / port the code in other platforms too but that is something we are not able to provide support for."
