### ISSUE TITLE
connection issues with android sdk

### ISSUE THREAD

**Issue by spalagat** [polarofficial/polar-ble-sdk#49]
i have downloaded the android sample application example and tried connecting my H10 sensor to the application, but the application is not able to detect the device properly. can you please guide me on how do i use the example application to connect to the device effectively, can you guys respond to it quickly as i have project submission deadline coming up.

**Comment by erkki-silvola** [comment]
Hi,

Easiest option is to use "auto connect" which will scan and connect to nearby device.

**Comment by spalagat** [comment]
Yes, I got it. By the way how do I stop scanning once Iam connected?

**Comment by erkki-silvola** [comment]
sdk should automatically stop scanning once connected
