### ISSUE TITLE
Android docs are duplicated

### ISSUE THREAD

**Issue by orestesgaolin** [polarofficial/polar-ble-sdk#490]
**Platform on which you observed the bug:** 
- [x] Android 
- [ ] iOS
- [ ] Other
- [ ] Platform is not relevant for this bug

**Device on which you observed the bug:**
- [ ] Polar OH1
- [ ] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [x] Device is not relevant for this bug

**Describe the bug**
With the recent [commit](https://github.com/polarofficial/polar-ble-sdk/compare/5.7.0...5.8.0?diff=unified&w=) the Android HTML docs got duplicated i.e. you can now open `polar-sdk-android/docs/index.html` (old) and `polar-sdk-android/docs/docs/index.html` (new)

**How to Reproduce**
-

**Expected behavior**
Please keep one version of docs

**Screenshots and logs**

![screenshot_20241016_144403](https://github.com/user-attachments/assets/0a952934-019d-4f39-b6ba-0f59e01e6760)

**Comment by samulimaa** [comment]
Hi, duplicate Android docs are now removed in commit: [780967240e68b00762db9a25e65db6d975cb3ccf](https://github.com/polarofficial/polar-ble-sdk/commit/780967240e68b00762db9a25e65db6d975cb3ccf)
