### ISSUE TITLE
doFirstTimeUse completes prematurely, before all underlying operations finish

### ISSUE THREAD

**Issue by korzonkiee** [polarofficial/polar-ble-sdk#494]
**Platform on which you observed the bug:** 
- [x] Android 
- [ ] iOS
- [ ] Other
- [ ] Platform is not relevant for this bug

**Device on which you observed the bug:**
- [ ] Polar OH1
- [ ] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [x] Other
- [x] Device is not relevant for this bug

**Describe the bug**
`doFirstTimeUse` completes as soon as FTU config is sent to the device ([here](https://github.com/polarofficial/polar-ble-sdk/blob/master/sources/Android/android-communications/library/src/sdk/java/com/polar/sdk/impl/BDBleApiImpl.kt#L1484)), but it should wait until other operations complete.

**How to Reproduce**
Call `doFirstTimeUse` method.

**Expected behavior**
`doFirstTimeUse` method should complete when all the underlying operations are finished.

**Screenshots and logs**
See video below that shows the execution order during debugging. 

<video src="https://github.com/user-attachments/assets/309b3ead-4069-49dd-ad5e-bb8cad86cca7" />

**Comment by samulimaa** [comment]
Hi, thanks for reporting this, we have created internal ticket to fix this on upcoming releases.

**Comment by samulimaa** [comment]
Fixed in SDK 5.9.0.

**Comment by samulimaa** [comment]
Hi, your PR looks good. However we can't directly merge these public SDK PRs because of our internal review and QA processes, but these fix proposals are greatly appreciated!

**Comment by palmqvisti** [comment]
FLOW-60982
