### ISSUE TITLE
polarblesdk not working with latest xcode/swift updates

### ISSUE THREAD

**Issue by Roberdan** [polarofficial/polar-ble-sdk#5]
hi, I just updated Xcode and I'm having this error message when trying to compile my project: 
"Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler: /Users/roberdan/Desktop/MirrorHR2.0/PolarBleSdk.framework/Modules/PolarBleSdk.swiftmodule/x86_64.swiftmodule", any help?
thanks a lot, RD

**Comment by erkki-silvola** [comment]
I will check this next week's tuesday.

**Comment by Roberdan** [comment]
any chance to recompile it earlier? we have a deadline and we are blocked :( thx

**Comment by erkki-silvola** [comment]
Sorry I cannot as I am on vacation still, and I don't have my MacBook with me.

**Comment by erkki-silvola** [comment]
Now there is swift 5 compatible sdk available. Note I still need to check demos and re-generate docs and testing before 1.1.0 release tag.
