### ISSUE TITLE
Swift 5.1.3 Support

### ISSUE THREAD

**Issue by GavinBryan** [polarofficial/polar-ble-sdk#50]
I'm unable to use framework in xcode 11.3 project due to the following warning:-

"Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.3 compiler:"

**Comment by erkki-silvola** [comment]
Hi, I will check this today

**Comment by erkki-silvola** [comment]
iOS SDK and dependencies are now build for Distribution, can you now try it ?

**Comment by GavinBryan** [comment]
@erkki-silvola thanks - building perfectly now with xcode 11.3
