### ISSUE TITLE
Polar Verity Sense - Not record when sensor off arm, and run functions on sensor firmware.

### ISSUE THREAD

**Issue by abbjetmus** [polarofficial/polar-ble-sdk#514]
***Platform your question concerns:*** 
- [ ] Android 
- [ ] iOS
- [ ] Other
- [ X] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [X ] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**
Hi! I have 3 question on Polar Verity Sense.

1. I wonder if the sensor is not on the arm and you have offline recording, does it continue to save data? I'd rather not have it do that, and have it automatically keep saving when the sensor is put on, is there a way to make that happen?

2. My second question is if it is possible to somehow run a function with standard deviation on the sensor so that you save only one accelerometer value that is standard deviation in a 5 second window? This way the memory will last much longer.

3. According to this link it has 2MB of offline memory storage.

[https://support.polar.com/en/how-to-use-polar-verity-sense-in-recording-mode](https://support.polar.com/en/how-to-use-polar-verity-sense-in-recording-mode)

 But from this site it says 600h of offline data. I don't understand the difference?
 [https://github.com/polarofficial/polar-ble-sdk/blob/master/documentation/OfflineRecordingExplained.md](https://github.com/polarofficial/polar-ble-sdk/blob/master/documentation/OfflineRecordingExplained.md)

**Comment by samulimaa** [comment]
Hi,

1. The recording does not detect whether the sensor is on the arm or not, it continues saving data regardless.
You could try to determine if it is being worn by analyzing heart rate data, but there is no built-in support for this.

2. Unfortunately, this feature is not supported. The sensor only provides raw data.

3. The memory limit of the Verity Sense is 2MB. If the memory reaches this limit, new recordings cannot be started.
The actual duration of a recording depends on the recording type and sampling rate.
