### ISSUE TITLE
[Question] PPG stream on OH1: Why 3 channels?

### ISSUE THREAD

**Issue by jul1u5** [polarofficial/polar-ble-sdk#52]
Looking at the Polar OH1 device, I can see six LEDs and only one photodyode. Why are there three separate values (ppg0, ppg1, ppg2) coming from the PPG stream?

**Comment by erkki-silvola** [comment]
Hi, 

The three separate values are LED pairs.

**Comment by jul1u5** [comment]
Ok, thanks for explaining!
