### ISSUE TITLE
Support to stride sensor

### ISSUE THREAD

**Issue by willianpaixao** [polarofficial/polar-ble-sdk#54]
The [stride sensor](https://www.polar.com/en/products/accessories/stride_sensor_bluetooth_smart) also uses Bluetooth Smart but seems not supported in the official API.

Any plans to add support to other devices than just the heart monitors?

**Comment by erkki-silvola** [comment]
Hi, 

Actually there is already implementation for RSC but not exposed through the SDK API, we will consider adding this

**Comment by willianpaixao** [comment]
What's RSC?

**Comment by erkki-silvola** [comment]
Short name for Running, Speed and Cadence

**Comment by willianpaixao** [comment]
Hi @erkki-silvola, any updates on this issue?

**Comment by samulimaa** [comment]
Hello, there are no near future plans to support the stride sensor.
