### ISSUE TITLE
Recording ACC data

### ISSUE THREAD

**Issue by hm1205** [polarofficial/polar-ble-sdk#60]
Dear all, 

is there any way to record acc data along with HR and RR ( in H10 and OH 1) ? In order to do some outdoor research without need of connectivity ... i mean with start recording method or using OH1 button. 

best regards thanks

**Comment by erkki-silvola** [comment]
Hi,

There is no support for internal storage of acc data.

**Comment by andYgnite** [comment]
Hi @hm1205,

you can now record ACC with the offline recording feature in Verity Sense:
https://github.com/polarofficial/polar-ble-sdk/blob/master/documentation/OfflineRecordingExplained.md
