### ISSUE TITLE
Multiple Sensor HR data response method update request.

### ISSUE THREAD

**Issue by jams032** [polarofficial/polar-ble-sdk#61]
Hello Polar Team,

I  am implementing Polar SDK (iOS) for polar H10 sensor in our existing fitness app. I can perform a session by connecting multiple H10 sensor. Sensor Connection and data providing works accordingly. Data receive are performed by using PolarBleApiDeviceHrObserver and

`func hrValueReceived(_ identifier: String, data: PolarHrData) { } `

method successfully.

Question 1 :
Here, hrValueReceived() method is called in every second for every device one time. But receiving data for n sensor , called the method n times in 1 second which leads to increase the complexity for post processing of the data. It's better for SDK to collect all connected sensors data in an array for a seconds and send back to implementation class/Delegate in every second rather than n times ( in 1 second) .

Does SDK provide this facility right now? How i can make this smooth ? 

Question 2 : Sensor disconnection works fine but if there is an invalid device ID is sent to 

`try api.disconnectFromDevice("\(device.DeviceID!)"`) , 

it shows a log (PolarBleSdk.InvalidArgument) from SDK. But no delegate method is called. 

Is it possible to get notify that user has requested a wrong device to disconnect ? 

Thanks.

**Comment by erkki-silvola** [comment]
Hi,

Question 1 :
SDK is only a "dummy" data transfer between sensor and app, and because of how ble works collecting data from multiple sensor and sending the collected chunk is not straight forward to do. So I believe you need to somehow handle this in the app itself.

Question 2 :
Yes PolarBleSdk.InvalidArgument is thrown if deviceId or address is incorrectly formatted and therefor there is no delegate callback invoked.

**Comment by jams032** [comment]
Thanks for your reply. Another related question.

We are trying to implement polar SDK in our existing fitness app. 
Polar SDK can connect any HR sensor like Wahoo TICKR because both (Polar H10, Wahoo TICKR) are manufactured for same purposes and perform with same API. Do you have any future plan to stop support connecting other Heart rate sensor (Wahoo TICKR or other ) from Polar SDK ? If not, we could continue with Polar SDK to connect all types of devices.

Thanks.

**Comment by erkki-silvola** [comment]
Hi,

The supported features won't be removed once they have been added.

**Comment by jams032** [comment]
@erkki-silvola  Hi ,

Polar SDK show pairing Request alert while connecting H10 sensor after calling api.connectToDevice(ID). 

This is annoying for the app we are working with. How to avoid this ?

**Comment by jams032** [comment]
Is it related to this ? 

https://stackoverflow.com/questions/29026377/ios-disable-bluetooth-pairing-request-popup
