### ISSUE TITLE
How to Get RR value in HeartRateMeasurement

### ISSUE THREAD

**Issue by ltvuongqn88** [polarofficial/polar-ble-sdk#65]
Dear Polar team,

Please help me get RR value from byte[] data received HeartRateMeasurementCharacteristic.ValueChanged.

I can get HR value by method:

public static ushort ParseHeartRateValue(byte[] data)
        {
            // Heart Rate profile defined flag values
            const byte heartRateValueFormat = 0x01;

            byte flags = data[0];
            bool isHeartRateValueSizeLong = ((flags & heartRateValueFormat) != 0);

            if (isHeartRateValueSizeLong)
            {
                return BitConverter.ToUInt16(data, 1);
            }
            else
            {
                return data[1];
            }
        }

**Comment by erkki-silvola** [comment]
Hi, there is source code dump you check from there

**Comment by jimmyzumthurm** [comment]
Hi, as @erkki-silvola  said, you can find RR data in PolarHrData, and there is flag to check if data is available or not : https://github.com/polarofficial/polar-ble-sdk/blob/fdb5bd0c485eecbfc857708f8f9c65efd02052ae/sources/Android/android-communications/library/src/sdk/java/com/polar/sdk/api/model/PolarHrData.kt#L4
