### ISSUE TITLE
Swift 5.2 Support

### ISSUE THREAD

**Issue by MattVanZyl** [polarofficial/polar-ble-sdk#67]
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler.

**Comment by erkki-silvola** [comment]
I updated on master the compiled sdk and rxswift. Release is coming later...

**Comment by JOikarinen** [comment]
Fixed in https://github.com/polarofficial/polar-ble-sdk/releases/tag/2.3.1
