### ISSUE TITLE
ECG output question

### ISSUE THREAD

**Issue by weapeul** [polarofficial/polar-ble-sdk#71]
How many seconds does the ECG data show on the logcat differ from the actual time?
The H10 sent 73 to 72 ECGs in bundles, how many frames per second is the ECG?
CH Cho.
Best regard.

**Comment by erkki-silvola** [comment]
Hi,

The ECG sample rate is between 128-131hz, this can be calculated from the timestamps.

**Comment by NiwreRelbag** [comment]
Hi Erkki,

recently one of our customers asked for a sampling rate >=200Hz. Is it possible to extend the SDK in that way? What is the internal sampling rate for the H10?

Thanks + best regards.
