### ISSUE TITLE
What is polarbleapi.polarfilter?

### ISSUE THREAD

**Issue by pajama** [polarofficial/polar-ble-sdk#74]
No noticeable difference toggling this value.

This is all I could find in the docs. 

![image](https://user-images.githubusercontent.com/2224105/79783790-0d01aa00-82f6-11ea-93ed-7de27b2ec388.png)

**Comment by erkki-silvola** [comment]
Hi,

Polar filter only affects scanning, whether is other than polar devices shown

**Comment by Whathecode** [comment]
Any BLE device? Or BLE devices with specific GATT services?

**Comment by JOikarinen** [comment]
@Whathecode any Polar BLE device.

**Comment by JOikarinen** [comment]
@pajama or @Whathecode if more questions related to polarFilter, please feel free to reopen this issue.
