### ISSUE TITLE
Accelerometer stream starts inconsistently

### ISSUE THREAD

**Issue by pajama** [polarofficial/polar-ble-sdk#75]
What are the requirements for getting the accelerometer stream to start? 

Occasionally the first launch will start streaming events immediately after the ready callback has fired. 

On subsequent launches, it can be very inconsistent. Despite the ready callback always firing, it can take a minute or longer for the events to start streaming.

**Comment by erkki-silvola** [comment]
Hi,

Device will request faster connection parameters, and depending on the phone etc.. it may take take some time to get desired parameters in use

**Comment by outsbook** [comment]
You need to start accelerometer stream after "**accelerometerFeatureReady**" callback

```
@Override
public void accelerometerFeatureReady(String identifier) {
      //start accelerometer stream here 
}
```

**Comment by pajama** [comment]
thanks @outsbook. I am already doing that.

**Comment by JOikarinen** [comment]
@pajama could you still recall what is the phone model you faced the problem? Which Polar model you used when noticing the problem,  Polar H10? I could try to repeat the issue.

**Comment by jimmyzumthurm** [comment]
Closing this as this has been stale for over 3 years
