### ISSUE TITLE
not working in background?

### ISSUE THREAD

**Issue by Roberdan** [polarofficial/polar-ble-sdk#8]
hi there,
I'm not able to have data from the HR sensor when the app is in background (background mode in the app is ok and other sensors are working fine), do you have any insight/suggestion?thanks, Rd

**Comment by erkki-silvola** [comment]
I just tested with polarBleSdkTestApp and it worked ok. What do you mean by "other sensors" ?

**Comment by Roberdan** [comment]
I see, the testapp works, for sure I'm doing something wrong but I do still have issues :(...what are the exact steps just for being sure it should work? thanks in advance

**Comment by erkki-silvola** [comment]
Is it so that immediately when app goes background hr notifications stops?

**Comment by Roberdan** [comment]
just few secs later, yes

**Comment by erkki-silvola** [comment]
Have you tried switching bt off/on or restarting the phone? One reason could be that os kills the app because of memory pressure etc. What is the phone/tablet model you are using?

**Comment by Roberdan** [comment]
tried, still same issue. Shall I call the startrecording/stoprecording functions? I was trying to use just the broadcasting. thx

**Comment by erkki-silvola** [comment]
Broadcast listening needs to have service in the scanning filter while on background which means broadcast hr listening only works when sensor is not connected somewhere else. Except H10 with dual connection enabled.
