### ISSUE TITLE
Two rr values in one measurement

### ISSUE THREAD

**Issue by nikolmamai** [polarofficial/polar-ble-sdk#80]
Hello,

I have noticed that hrNotificationReceived function could sometimes return two rr values in one measurement. Since, a hertbeat is the peek of an R wave, and rr interval is the time elapsed between two successive R waves, should api just return only one value? Could you explain when above case happens?

**Comment by outsbook** [comment]
There is basically 4 RR Interval for each notification 
So, if you got 2 then other two are 0
Sometime you got 3 or 4 or 1

**Comment by dlxm455** [comment]
> There is basically 4 RR Interval for each notification
> So, if you got 2 then other two are 0
> Sometime you got 3 or 4 or 1
Hi @outsbook, could you please explain this a bit more? I noticed that the data (notification) comes about every 1s. If the heart rate is around 60bpm - 100bpm, it should has 1 or 2 RR interval per second. Why are there 4 RR interval for each notification? Thanks.

**Comment by JOikarinen** [comment]
From the [Heart Rate Service specification](https://www.bluetooth.org/docman/handlers/downloaddoc.ashx?doc_id=239866):

> **3.1.1.5 Transmission Interval**
> In typical applications, the Heart Rate Measurement characteristic is notified approximately 1 time per second 
- So for example, if the Heart Rate Service decides to send heart rate notification around once per second. Following will happen:
    - if the heart rate is higher than 60 bpm then the Heart Rate service sends two RR samples per heart rate notification every now and then
    - if the heart rate is 120 bpm then the Heart Rate service sends two RR samples per heart rate notification.
    - if the heart rate is higher than 120 bpm then the Heart Rate service sends three RR samples per heart rate notification every now and then
    - and so on ...
