### ISSUE TITLE
How to set polar OH1 time

### ISSUE THREAD

**Issue by Eagleseb** [polarofficial/polar-ble-sdk#86]
Hey, I'm using python to communicate with the OH1 sensor using BLE standard. I can't find any documentation about how to set up its time.
Looking at the source code, I found out that I need to send the new time value to the RFC77_PFTP_MTU_CHARACTERISTIC that has UUID "FB005C51-02E7-F387-1CAD-8ACD2D8DF0C8", but I don't know what is the format of the hexadecimal data I should send. Could you please provide some example ?

Thanks a lot

**Comment by JOikarinen** [comment]
Unfortunately, we are only able to support Android and iOS. The SKD includes source code and you can feel free to utilize / port the code in other platforms too but that is something we are not able to provide support for.
