### ISSUE TITLE
Swift complier issue

### ISSUE THREAD

**Issue by hm1205** [polarofficial/polar-ble-sdk#88]
hi, 

my Xcode and Mac OS X had been updated and now I'm getting : 
Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.2.4 compiler
error on polar module import. 
could you please update the git repository with a new compile version ? 

best regard

**Comment by Narragansett** [comment]
ibid.  This has been open for over a month, can someone fix this, please?

**Comment by erkki-silvola** [comment]
I suggest to compile the sdk and deps from source for now sdk will be updated later
