### ISSUE TITLE
OH1 Heart Rate SDK vs Polar Flow

### ISSUE THREAD

**Issue by msfine0226** [polarofficial/polar-ble-sdk#89]
For the OH1, is the heart rate returned by the SDK (from the sensor itself) the same as the heart rate I would download from Polar, if I was using the Polar Flow app?  Or, does Polar apply post processing on its server to improve the accuracy of the heart rate?

**Comment by JOikarinen** [comment]
@msfine0226 heart rate returned by the SDK is exactly the same what Polar Flow mobile app and Polar Flow web gets from the sensor. Polar proprietary apps may manipulate the received data for some purposes, like for smoothening graphical representation.
