### ISSUE TITLE
`backgroundEntered` and `foregroundEntered` methods in foreground service

### ISSUE THREAD

**Issue by jul1u5** [polarofficial/polar-ble-sdk#96]
As far as I have seen, the `backgroundEntered` method enables some scan filter when app is in background. I use Polar SDK in a foreground service that runs while the app is in background and records streams from connected devices. Do I still need call `backgroundEntered`/`foregroundEntered` methods?

Sorry for creating so many issues :P

**Comment by JOikarinen** [comment]
@jul1u5 by calling `backgroundEntered` SDK connects to the sensor if the connection is lost while your app in background. If you don't call `backgroundEntered` the sensor connection is maintained, however if the connection is lost during your app is background the automatic reconnection won't happen.
