### ISSUE TITLE
iOS requiresUISupportedExternalAccessoryProtocols plus your Apple PPID for review

### ISSUE THREAD

**Issue by Narragansett** [polarofficial/polar-ble-sdk#99]
Developing iOS apps for the Polar H10 device ... my app got rejected because ...

I need to add ‘UISupportedExternalAccessoryProtocols' in my Info.plist and to include the Polar devices PPID in the notes for App Review.

From here - what value of the protocols do I enter that your device uses?
https://developer.apple.com/documentation/bundleresources/information_property_list/uisupportedexternalaccessoryprotocols

This page says I shouldn’t need to join MFi: https://mfi.apple.com/MFiWeb/getFAQ.action#4-0

I likely need to provide the Polar PPID (Product Plan ID), what is yours?

**Comment by JOikarinen** [comment]
If using PolarSDK in your application you shall not need to define UISupportedExternalAccessoryProtocols in your Info.plist. 

Could it be you have other Background mode flags set than "Uses Bluetooth LE accessories" or "Act as Bluetooth LE accessory"
<img width="884" alt="Screenshot 2021-01-15 at 13 58 29" src="https://user-images.githubusercontent.com/12439855/104724877-fa5bba80-5739-11eb-9233-6d22f5abef6a.png">
